"""TkShell — the top-level window chrome, rail, status bar, and tool runner.

Responsibilities
----------------
* Win11-style title bar (title text + SF monogram chip)
* Left rail (220 px) — groups from BaseTool.group, sorted (group, order, label)
  plus static Instructions / About / User rows below a divider.
* Status bar (22 px) — live status left, version + email right.
* Content area — auto-generates each tool's frame from tool.inputs dispatched
  to the right primitive, plus output FileRow when tool.output is set.
* Primary button — disables inputs, spawns worker via ThreadPoolExecutor,
  marshals progress/completion to Tk via root.after(0, ...).
* Secondary buttons from tool.secondary_actions().
* Tool switching preserves per-tool input values in memory.
* Global exception handler → danger banner + log path.
"""

from __future__ import annotations

import logging
import tkinter as tk
import tkinter.font as tkfont
import tkinter.messagebox as messagebox
import tkinter.ttk as ttk
import traceback
from collections.abc import Callable
from concurrent.futures import Future, ThreadPoolExecutor
from pathlib import Path
from typing import Any

import app_metadata
from app_metadata import APP_TITLE, APP_VERSION, SUPPORT_EMAIL
from toolkit import tokens
from toolkit.base_tool import (
    BaseTool,
    CurrencyInput,
    DateInput,
    FileInput,
    InputSpec,
    NumberInput,
    OutputSpec,
    RangeInput,
    SecretInput,
    TableSpec,
    TextInput,
    ToolResult,
)
from toolkit.fonts import FontMap
from toolkit.primitives import (
    Banner,
    CurrencyField,
    DateField,
    FileRow,
    LogView,
    Metric,
    NumberField,
    ProgressBar,
    SecretField,
    SectionHeader,
    SelectableList,
    Table,
    TextField,
)
from toolkit.user_frame import UserFrame

logger = logging.getLogger(__name__)

# Type alias for the value-bearing widget dict kept per tool.
_WidgetMap = dict[str, Any]


def _filter_rows(rows: list[dict[str, Any]], filter_key: str) -> list[dict[str, Any]]:
    """Return the subset of *rows* whose ``_faculty`` value equals *filter_key*.

    Pure function — no Tk dependency. Extracted so tests can exercise the
    filter logic on Linux CI where Tkinter is absent.
    """
    return [r for r in rows if r.get("_faculty") == filter_key]


_CASES21_PO_HELP_TEXT = """How to save a CASES21 Purchase Order as a PDF

Purchase Orders uploaded to School Tool are validated by the system. Anything \
generated directly by CASES21 or Compass is recognised automatically and \
unlocks your paid tools within seconds. To upload a CASES21 PO, you first \
need to save it out of CASES21 as a PDF. Here's how.


BEFORE YOU START

  • Make sure you are signed in to CASES21 with your usual credentials.
  • Know the PO number (or supplier / date) of the Purchase Order you \
want to save. If you've just generated the invoice through School Tool, \
look for the matching PO your school finance office raised against it.


STEP-BY-STEP

  1. In CASES21, open the Finance module.

  2. Navigate to Accounts Payable → Purchase Orders.

  3. Use the search filters (PO number, supplier name, or date range) to \
find the PO you want. Highlight the PO row in the list.

  4. Click Print (or press Ctrl+P). The Windows Print dialog opens.

  5. Under Printer, choose Microsoft Print to PDF.
     If you don't see that option, pick any PDF printer that's installed, \
or install one (Foxit Reader and PDFCreator are both free).

  6. Click Print.

  7. In the Save Print Output As window:
       • Pick a folder you'll remember (e.g. Documents \\ School Tool).
       • Name the file clearly — for example PO_P024900.pdf.
       • Click Save.

  8. In School Tool, go to User → Service → Upload signed PO and \
pick the PDF you just saved.


WHAT HAPPENS NEXT

  • If the PO was generated by CASES21 (or Compass), School Tool \
validates it instantly. You'll see the licence status flip to Active and \
your paid tools unlock right away.

  • If the PO is scanned or non-standard, it enters a manual review \
queue. We usually respond within one business day.


TROUBLESHOOTING

  • "Microsoft Print to PDF" missing — open Windows Settings \
→ Apps → Optional features, search for "Microsoft Print to PDF", \
and install it. Restart the Print dialog afterwards.

  • PDF opens blank — you may have printed the list view rather \
than the PO itself. Open the PO first (double-click it), then print.

  • Upload fails in School Tool — check the file is under 10 MB \
and is actually a .pdf (not .docx or a photo). Retry from User → \
Service.


SUPPORT

  School Tool feedback — Vurctne@gmail.com
  DoE schools finance help — schools.finance.support@education.vic.gov.au
"""


class TkShell(ttk.Frame):
    """Top-level shell frame — pack into the root Tk window with fill=both, expand=True."""

    def __init__(
        self,
        root: tk.Tk,
        fonts: FontMap,
        tools: list[type[BaseTool]],
        log_path: Path | None = None,
        **kwargs: Any,
    ) -> None:
        super().__init__(root, **kwargs)

        self._root = root
        self._fonts = fonts
        self._log_path = log_path

        # Instantiate each tool class → instance
        # tools is a list[type[BaseTool]] from registry.all_tools()
        self._tools: list[BaseTool] = [cls() for cls in tools]
        self._tool_map: dict[str, BaseTool] = {t.id: t for t in self._tools}

        # Per-tool cached input values (preserved across tab switches)
        self._input_cache: dict[str, dict[str, Any]] = {t.id: {} for t in self._tools}

        # Active tool
        self._active_id: str = self._tools[0].id if self._tools else ""

        # User tab (built lazily on first activation)
        self._user_frame: UserFrame | None = None

        # Unlock CTA frame (built lazily on first gated activation)
        self._unlock_frame: tk.Frame | None = None
        self._unlock_title_var: tk.StringVar | None = None

        # Per-tool executor (one per tool instance so runs don't queue globally)
        self._executors: dict[str, ThreadPoolExecutor] = {
            t.id: ThreadPoolExecutor(max_workers=1) for t in self._tools
        }

        # Per-tool filter state (transient UI — not part of ToolResult)
        self._tool_filter: dict[str, str | None] = {}
        self._tool_table_specs: dict[str, TableSpec | None] = {}
        self._tool_rails: dict[str, SelectableList | None] = {}
        self._tool_filter_chips: dict[str, tk.Frame | None] = {}

        # Per-tool debounce after() IDs for RangeInput live-preview callbacks.
        # Maps tool_id -> {input_key -> after_id | None}
        self._range_debounce: dict[str, dict[str, str | None]] = {}

        # Root-window <Configure> debounce (Fix 2 — Round 13).
        # Fires once per ~50 ms idle after any window-resize drag, preventing
        # Tk's geometry manager from thrashing on every pixel.
        self._root_configure_after: str | None = None

        # Drag-state suspension (Fix 5 — Round 17).
        # While the user is actively dragging the window edge the root
        # <Configure> fires on every pixel.  We set _drag_active=True on the
        # first event and let all canvas Configure handlers skip their work
        # entirely.  _on_drag_settled() runs 150 ms after the last Configure
        # event and triggers a single clean layout pass, then clears the flag.
        # This is more aggressive than debouncing alone (which still schedules
        # an after() call on every pixel); suspension drops ALL intermediate
        # work during the drag.  The 150 ms settle window is longer than the
        # 100 ms debounce so it acts as the outer gate.
        self._drag_active: bool = False
        self._drag_settle_after: str | None = None

        # Per-tool pending canvas-configure callbacks that were skipped during
        # drag; we re-fire them once on settle.  Each entry is a 0-arg callable.
        self._pending_canvas_configures: list[Any] = []

        # Install global exception handler
        self._root.report_callback_exception = self._handle_tk_exception

        # Build layout
        self._build_layout()

        # Activate first tool
        if self._active_id:
            self._activate_tool(self._active_id)

    # -----------------------------------------------------------------------
    # Layout construction
    # -----------------------------------------------------------------------

    def _build_layout(self) -> None:
        """Construct the shell: app header | (rail | content) | status bar."""
        self.configure(style="TFrame")

        # Fix row height to a constant so Tk skips per-resize row-height
        # recomputation inside Treeview.  22 px matches the design's 4 px grid
        # (font ~13 px + 4 px padding above + 4 px below ≈ 21-22 px).
        # Without this Tk measures each row's font metrics on every Configure
        # event, which adds measurable work during window-drag.  (Round 14)
        _style = ttk.Style()
        _style.configure("Treeview", rowheight=22)

        # Round 19 — derived button style for "launcher" tools that present a
        # single oversized call-to-action (e.g. Refined PAL Search).  Tools
        # opt-in by setting ``primary_button_style = "Large.Accent.TButton"``;
        # the default remains ``Accent.TButton`` for every other tool so the
        # broad design contract from ADR-0014 stays intact.
        _style.configure(
            "Large.Accent.TButton",
            font=(self._fonts.sans_family, tokens.FS_14, "bold"),
            padding=(tokens.SP_4, tokens.SP_3),
        )

        # App header row (32 px) — SF chip + active-tool title
        self._app_header = self._build_app_header()
        self._app_header.pack(side="top", fill="x")

        # Outer vertical split: body + status bar
        self._body_frame = ttk.Frame(self)
        self._body_frame.pack(side="top", fill="both", expand=True)

        self._status_bar = self._build_status_bar()
        self._status_bar.pack(side="bottom", fill="x")

        # Horizontal split inside body: rail | content
        #
        # ADR-0014 deliberate exception (Round 19): the left rail's width was
        # previously locked at 220 px.  Users requested a draggable handle so
        # long tool labels and group headers can fit comfortably without
        # forcing every label to fit the original width.  We now hold the rail
        # and content panes inside a tk.PanedWindow so the user can drag the
        # divider; the 220 px default and a 180 px minsize preserve the design
        # intent for users who never touch the sash.
        self._body_paned = tk.PanedWindow(
            self._body_frame,
            orient=tk.HORIZONTAL,
            sashwidth=4,
            sashrelief=tk.FLAT,
            bg=tokens.BORDER_SUBTLE,
            borderwidth=0,
            showhandle=False,
            opaqueresize=False,
        )
        self._body_paned.pack(side="left", fill="both", expand=True)

        self._rail_frame = self._build_rail(parent=self._body_paned)
        self._content_outer = tk.Frame(self._body_paned, bg=tokens.BG_MUTED)

        # Pane 1 — rail.  The rail itself is built with width=220 and
        # pack_propagate(False), so the PanedWindow uses 220 as the initial
        # sash position.  minsize=180 stops the rail from collapsing past the
        # point at which tool labels truncate; stretch="never" keeps the rail
        # at its current width when the window resizes.
        self._body_paned.add(self._rail_frame, minsize=180, stretch="never")
        # Pane 2 — content.  stretch="always" makes the content area absorb
        # window-size changes; the rail width stays as the user left it.
        self._body_paned.add(self._content_outer, minsize=400, stretch="always")

        # Tool content frames (one per tool, stacked — only one visible at once)
        self._tool_frames: dict[str, tk.Frame] = {}
        self._tool_widgets: dict[str, _WidgetMap] = {}
        self._tool_banners: dict[str, Banner | None] = {}
        self._tool_progress: dict[str, ProgressBar | None] = {}
        self._tool_logviews: dict[str, LogView | None] = {}
        self._tool_tables: dict[str, Table | None] = {}
        self._tool_metric_frames: dict[str, tk.Frame | None] = {}
        self._tool_primary_btns: dict[str, ttk.Button | None] = {}
        self._tool_output_rows: dict[str, FileRow | None] = {}

        for tool in self._tools:
            frame, wmap = self._build_tool_frame(tool)
            # Do NOT pre-place all frames.  Only the active frame is placed at
            # any one time (see _activate_tool / _show_unlock_cta / _show_user).
            # Placing every frame with relwidth/relheight=1.0 causes Tk to fire
            # <Configure> on ALL of them — even the hidden (lowered) ones — on
            # every resize tick, multiplying layout work by the tool count.
            # (Fix 2 — Round 13)
            self._tool_frames[tool.id] = frame
            self._tool_widgets[tool.id] = wmap

        # Root-window resize debounce — one global handler as a safety net.
        # Fires only after the user has stopped dragging for ~100 ms (raised
        # from 50 ms in Round 14), which ensures any stray layout callbacks
        # settle without thrashing.
        self._root.bind("<Configure>", self._on_root_configure)

    def _build_app_header(self) -> tk.Frame:
        """32 px app-level header — navy SF chip with active tool's short mark + title text.

        Sits above the body; OS chrome sits above this. Matches the design handoff's
        ``desktop_multitool/tk-shell.jsx`` artboard (chip + title, no custom min/max/close).
        """
        header = tk.Frame(self, bg=tokens.BG_MUTED, height=32)
        header.pack_propagate(False)

        inner = tk.Frame(header, bg=tokens.BG_MUTED)
        inner.pack(fill="both", expand=True, padx=tokens.SP_3)

        # SF monogram chip: 16x16 navy square with the active tool's short mark.
        # Height is clamped via a frame wrapper so the label renders at exactly 16 px.
        chip_wrap = tk.Frame(inner, bg=tokens.BG_MUTED, width=16, height=16)
        chip_wrap.pack_propagate(False)
        chip_wrap.pack(side="left", pady=(tokens.SP_2, tokens.SP_2))

        self._header_chip = tk.Label(
            chip_wrap,
            text="",
            bg=tokens.BRAND_NAVY,
            fg=tokens.FG_INVERSE,
            font=tkfont.Font(family=self._fonts.sans_family, size=8, weight="bold"),
            anchor="center",
        )
        self._header_chip.pack(fill="both", expand=True)

        # Title text — updated on tool activation.
        self._header_title_var = tk.StringVar(value=APP_TITLE)
        tk.Label(
            inner,
            textvariable=self._header_title_var,
            bg=tokens.BG_MUTED,
            fg=tokens.FG_1,
            font=tkfont.Font(family=self._fonts.sans_family, size=tokens.FS_12),
            anchor="w",
        ).pack(side="left", padx=(tokens.SP_3, 0))

        # 1 px bottom border
        tk.Frame(header, bg=tokens.BORDER_SUBTLE, height=1).pack(side="bottom", fill="x")

        return header

    def _build_status_bar(self) -> tk.Frame:
        bar = tk.Frame(
            self._body_frame,
            bg=tokens.BG_MUTED,
            height=22,
        )
        bar.pack_propagate(False)

        # 1 px top border
        sep = tk.Frame(bar, bg=tokens.BORDER_SUBTLE, height=1)
        sep.pack(side="top", fill="x")

        inner = tk.Frame(bar, bg=tokens.BG_MUTED)
        inner.pack(fill="both", expand=True, padx=tokens.SP_3)

        self._status_left_var = tk.StringVar(value="Ready")
        left = tk.Label(
            inner,
            textvariable=self._status_left_var,
            fg=tokens.FG_MUTED,
            bg=tokens.BG_MUTED,
            font=self._small_font(),
            anchor="w",
        )
        left.pack(side="left", fill="x", expand=True)

        right_text = f"v{APP_VERSION} · {SUPPORT_EMAIL}"
        right = tk.Label(
            inner,
            text=right_text,
            fg=tokens.FG_MUTED,
            bg=tokens.BG_MUTED,
            font=self._small_font(),
            anchor="e",
        )
        right.pack(side="right")

        return bar

    def _build_rail(self, parent: tk.Widget | None = None) -> tk.Frame:
        """Build the 220 px left rail with grouped tool entries.

        ``parent`` defaults to the body frame for backward compatibility, but
        the live shell now wraps the rail in a ``tk.PanedWindow`` and passes
        that PanedWindow in so the user can drag the rail width (Round 19).
        """
        rail = tk.Frame(
            parent if parent is not None else self._body_frame,
            bg=tokens.BG_PANEL,
            width=220,
        )
        rail.pack_propagate(False)

        # 1 px right border
        border = tk.Frame(rail, bg=tokens.BORDER_SUBTLE, width=1)
        border.pack(side="right", fill="y")

        scroll_container = tk.Frame(rail, bg=tokens.BG_PANEL)
        scroll_container.pack(side="left", fill="both", expand=True, pady=tokens.SP_1)

        # Group tools
        groups: dict[str, list[BaseTool]] = {}
        for tool in sorted(self._tools, key=lambda t: (t.group, t.order, t.label)):
            groups.setdefault(tool.group, []).append(tool)

        self._rail_items: dict[str, tk.Label] = {}

        for group_name, group_tools in groups.items():
            # Group header
            grp_lbl = tk.Label(
                scroll_container,
                text=f"▾ {group_name}",
                bg=tokens.BG_PANEL,
                fg=tokens.FG_1,
                font=self._group_header_font(),
                anchor="w",
                padx=tokens.SP_2,
                pady=tokens.SP_1,
            )
            grp_lbl.pack(fill="x")

            for tool in group_tools:
                item = tk.Label(
                    scroll_container,
                    text=tool.label,
                    bg=tokens.BG_PANEL,
                    fg=tokens.FG_1,
                    font=self._rail_font(),
                    anchor="w",
                    padx=30,
                    pady=tokens.SP_1,
                    cursor="hand2",
                )
                item.pack(fill="x")
                tid = tool.id
                item.bind("<Button-1>", lambda _e, t=tid: self._activate_tool(t))  # type: ignore[misc]
                item.bind("<Enter>", lambda _e, w=item, t=tid: self._rail_hover(w, t))  # type: ignore[misc]
                item.bind("<Leave>", lambda _e, w=item, t=tid: self._rail_unhover(w, t))  # type: ignore[misc]
                self._rail_items[tool.id] = item

        # "In development" section — non-clickable placeholders for tools that
        # are designed but not yet shipped, or temporarily parked.
        from toolkit.registry import IN_DEVELOPMENT_TOOLS

        if IN_DEVELOPMENT_TOOLS:
            indev_header = tk.Label(
                scroll_container,
                text="In development",
                bg=tokens.BG_PANEL,
                fg=tokens.FG_3,
                font=self._group_header_font(),
                anchor="w",
                padx=tokens.SP_2,
                pady=tokens.SP_1,
            )
            indev_header.pack(fill="x")

            for _group, label, _short, _reason in IN_DEVELOPMENT_TOOLS:
                item = tk.Label(
                    scroll_container,
                    text=label,
                    bg=tokens.BG_PANEL,
                    fg=tokens.FG_3,
                    font=self._rail_font(),
                    anchor="w",
                    padx=30,
                    pady=tokens.SP_1,
                )
                item.pack(fill="x")
                # No <Button-1> binding — these entries are non-clickable.

        # Divider
        div = tk.Frame(scroll_container, bg=tokens.BORDER_SUBTLE, height=1)
        div.pack(fill="x", padx=tokens.SP_3, pady=(tokens.SP_2, tokens.SP_1))

        # Static entries: Instructions, Privacy Policy. User gated by SHOW_USER_TAB.
        # Round 21 — replaced "About" (basic version + email blurb) with
        # "Privacy Policy" because that's what users actually need a link
        # to. The privacy text is loaded from docs/store_privacy_policy.md
        # and rendered using the same scrollable help-window primitive used
        # for tool instructions.
        static_entries: list[tuple[str, Any]] = [
            ("Instructions", self._show_instructions),
            ("Privacy Policy", self._show_privacy_policy),
        ]
        if app_metadata.SHOW_USER_TAB:
            static_entries.append(("User", self._show_user))

        for entry_label, callback in static_entries:
            lbl = tk.Label(
                scroll_container,
                text=entry_label,
                bg=tokens.BG_PANEL,
                fg=tokens.FG_1,
                font=self._rail_font(),
                anchor="w",
                padx=tokens.SP_3,
                pady=3,
                cursor="hand2",
            )
            lbl.pack(fill="x")
            lbl.bind("<Button-1>", lambda _e, cb=callback: cb())  # type: ignore[misc]

        return rail

    def _build_tool_frame(self, tool: BaseTool) -> tuple[tk.Frame, _WidgetMap]:
        """Build the full content frame for a single tool. Returns (frame, widget_map)."""
        frame = tk.Frame(self._content_outer, bg=tokens.BG_MUTED)
        widget_map: _WidgetMap = {}

        # Scrollable canvas for the content
        canvas = tk.Canvas(frame, bg=tokens.BG_MUTED, highlightthickness=0)
        vsb = ttk.Scrollbar(frame, orient="vertical", command=canvas.yview)
        canvas.configure(yscrollcommand=vsb.set)

        vsb.pack(side="right", fill="y")
        canvas.pack(side="left", fill="both", expand=True)

        inner = tk.Frame(canvas, bg=tokens.BG_MUTED)
        canvas_window = canvas.create_window((0, 0), window=inner, anchor="nw")

        # Debounce after() IDs — cancel-and-reschedule so layout math runs only
        # once per ~100 ms idle window, not on every pixel of a window-resize drag.
        # 100 ms (raised from 50 ms in Round 14) reduces flicker frequency at the
        # cost of slightly slower settle; the bigger win is that inactive tool frames
        # are place_forget()-ed so they receive no Configure events at all.
        # This matches the pattern used in SelectableList (Round 9 fix).
        _inner_configure_after: list[str | None] = [None]
        _canvas_configure_after: list[str | None] = [None]

        def _do_inner_configure() -> None:
            # Fired only when the INNER FRAME's content changes (children
            # rearranging or fonts changing) — not on every window resize.
            # scrollregion tracks the inner content's natural bbox; it does NOT
            # need updating when only the canvas width changes.  (Round 14)
            _inner_configure_after[0] = None
            try:
                canvas.configure(scrollregion=canvas.bbox("all"))
            except tk.TclError:
                pass

        def _on_inner_configure(_e: Any) -> None:
            if _inner_configure_after[0] is not None:
                try:
                    canvas.after_cancel(_inner_configure_after[0])
                except tk.TclError:
                    pass
            _inner_configure_after[0] = canvas.after(100, _do_inner_configure)

        def _do_canvas_configure(w: int) -> None:
            # Fired only when the CANVAS width changes (window resize).
            # Updates the inner window width so horizontal content stretches.
            # scrollregion is NOT recomputed here — that's the inner-frame's job.
            # (Round 14)
            _canvas_configure_after[0] = None
            try:
                canvas.itemconfigure(canvas_window, width=w)
            except tk.TclError:
                pass

        def _on_canvas_configure(e: Any) -> None:
            w = e.width
            # Fix 5 (Round 17): during an active window-edge drag skip all
            # intermediate layout work — record the latest width as a pending
            # callback and return immediately.  _on_drag_settled() will fire it
            # once 150 ms after the drag ends.  This eliminates the after()
            # scheduling overhead on every pixel of a resize drag.
            if self._drag_active:
                # Replace any previously-queued pending callback for this canvas
                # so only the last width is used when drag settles.
                cb = lambda: _do_canvas_configure(w)  # noqa: E731
                # Remove any earlier pending entry for this canvas (identified by
                # canvas identity) by filtering on the closure's __code__ object
                # is not reliable — we use a sentinel list instead.
                self._pending_canvas_configures.append(cb)
                return
            if _canvas_configure_after[0] is not None:
                try:
                    canvas.after_cancel(_canvas_configure_after[0])
                except tk.TclError:
                    pass
            _canvas_configure_after[0] = canvas.after(100, lambda: _do_canvas_configure(w))

        inner.bind("<Configure>", _on_inner_configure)
        canvas.bind("<Configure>", _on_canvas_configure)

        pad = tokens.SP_4  # 16 px
        gap = tokens.SP_GAP_SECTION  # 10 px per design spec

        def section(pady_top: int = 0) -> tk.Frame:
            f = tk.Frame(inner, bg=tokens.BG_MUTED)
            f.pack(fill="x", padx=pad, pady=(pady_top, 0))
            return f

        # Section header
        hdr_frame = section(pad)
        sh = SectionHeader(hdr_frame, title=tool.label)
        sh.pack(fill="x")

        has_output = tool.output is not None

        # Input fields
        for inp in tool.inputs:
            inp_frame = section(gap)
            w = self._build_input_widget(inp_frame, inp, tool)
            w.pack(fill="x")
            widget_map[inp.key] = w

        # Output file row (only when tool.output is set)
        output_row: FileRow | None = None
        if has_output and tool.output is not None:
            out_spec: OutputSpec = tool.output
            out_frame = section(gap)
            out_row_label = out_spec.label or "Output file"

            def _on_output_pick(p: Path, key: str = out_spec.key) -> None:
                self._input_cache[tool.id][key] = p

            output_row = FileRow(
                out_frame,
                label=out_row_label,
                on_pick=_on_output_pick,
                filetypes=[
                    (f"{out_spec.suffix.lstrip('.')} files", f"*{out_spec.suffix}"),
                    ("All files", "*.*"),
                ],
                optional=False,
            )
            output_row.pack(fill="x")

        self._tool_output_rows[tool.id] = output_row

        # --- Action button row ---
        btn_frame = section(gap + tokens.SP_1)
        btn_inner = tk.Frame(btn_frame, bg=tokens.BG_MUTED)
        btn_inner.pack(anchor="w")

        # Tools may opt into a derived ttk style (e.g. "Large.Accent.TButton")
        # via an optional ``primary_button_style`` class attribute.  Default
        # is the standard "Accent.TButton" used everywhere else in the shell.
        # ``getattr`` keeps this backward-compatible for tools that have not
        # declared the attribute on their class.  (Round 19)
        _primary_style = getattr(tool, "primary_button_style", "Accent.TButton")
        primary_btn: ttk.Button = ttk.Button(
            btn_inner,
            text=tool.primary_button,
            command=lambda t=tool: self._run_tool(t),  # type: ignore[misc]
            style=_primary_style,
        )
        primary_btn.pack(side="left", padx=(0, tokens.SP_2))
        self._tool_primary_btns[tool.id] = primary_btn

        # Secondary actions
        for sec_label, sec_cmd in tool.secondary_actions():
            sec_btn = ttk.Button(btn_inner, text=sec_label, command=sec_cmd)
            sec_btn.pack(side="left", padx=(0, tokens.SP_1))

        # Press-and-hold reveal buttons (Round 21).  Tools may declare an
        # optional ``press_hold_actions(self) -> list[tuple[str, Callable[[], str]]]``
        # method.  Each entry becomes a button paired with a small grey
        # label: while the user holds the left mouse button, the label
        # shows the text returned by the callable; on release (or pointer
        # leaving the button) the label clears.  Designed for HYIA's
        # "show calculation formula" pattern where exposing the value
        # constantly defeats the safeguard but the user wants to verify it.
        press_hold_fn = getattr(tool, "press_hold_actions", None)
        if callable(press_hold_fn):
            for ph_label, ph_get_text in press_hold_fn():
                self._make_press_hold_button(btn_inner, ph_label, ph_get_text)

        # Clear button — always last in the action row (per design)
        clear_btn = ttk.Button(
            btn_inner,
            text="Clear",
            command=lambda t=tool: self._clear_tool(t),  # type: ignore[misc]
        )
        clear_btn.pack(side="left", padx=(0, tokens.SP_1))

        # --- Banner (hidden until result) ---
        banner_frame = section(gap)
        banner: Banner | None = None
        self._tool_banners[tool.id] = banner
        widget_map["__banner_frame__"] = banner_frame

        # --- Progress bar (hidden until running) ---
        pb_frame = section(gap)
        pb = ProgressBar(pb_frame)
        pb.pack(fill="x")
        pb_frame.pack_forget()  # hidden initially
        self._tool_progress[tool.id] = pb
        widget_map["__pb_frame__"] = pb_frame

        # --- Metric area (populated after run) ---
        metric_frame = section(gap)
        metric_frame.pack_forget()
        self._tool_metric_frames[tool.id] = metric_frame

        # --- Log view ---
        log_frame = section(gap)
        lv = LogView(log_frame)
        lv.pack(fill="both", expand=True)
        log_frame.pack_forget()
        self._tool_logviews[tool.id] = lv
        widget_map["__log_frame__"] = log_frame

        # --- Table ---
        table_frame = section(gap)
        self._tool_tables[tool.id] = None  # created lazily on result
        widget_map["__table_frame__"] = table_frame
        table_frame.pack_forget()

        # --- Filter chip (shown only when a rail filter is active) ---
        chip_frame = section(0)
        chip_frame.pack_forget()
        self._tool_filter_chips[tool.id] = chip_frame
        self._tool_filter[tool.id] = None
        self._tool_table_specs[tool.id] = None
        self._tool_rails[tool.id] = None
        widget_map["__chip_frame__"] = chip_frame

        # --- Muted footer ---
        footer_frame = section(gap)
        footer = tk.Label(
            footer_frame,
            text=f"Please send feedback to {SUPPORT_EMAIL}",
            fg=tokens.FG_3,
            bg=tokens.BG_MUTED,
            font=self._small_font(),
            anchor="w",
        )
        footer.pack(fill="x", pady=(0, pad))

        return frame, widget_map

    def _build_input_widget(self, parent: tk.Widget, inp: InputSpec, tool: BaseTool) -> tk.Widget:
        """Dispatch an InputSpec → the matching primitive widget."""
        if isinstance(inp, FileInput):
            cached = self._input_cache[tool.id].get(inp.key)

            def _on_pick(p: Path, key: str = inp.key, tid: str = tool.id) -> None:
                self._input_cache[tid][key] = p

            return FileRow(
                parent,
                label=inp.label,
                on_pick=_on_pick,
                filetypes=inp.filetypes if inp.filetypes else [("All files", "*.*")],
                initial_path=cached if isinstance(cached, Path) else None,
            )

        if isinstance(inp, TextInput):
            cached = str(self._input_cache[tool.id].get(inp.key, ""))
            return TextField(
                parent,
                label=inp.label,
                value=cached,
                placeholder=inp.placeholder,
                max_length=inp.max_length,
            )

        if isinstance(inp, NumberInput):
            cached = str(self._input_cache[tool.id].get(inp.key, ""))
            return NumberField(
                parent,
                label=inp.label,
                value=cached,
                min_value=inp.min_value,
                max_value=inp.max_value,
                decimals=inp.decimals,
            )

        if isinstance(inp, CurrencyInput):
            cached = str(self._input_cache[tool.id].get(inp.key, ""))
            return CurrencyField(parent, label=inp.label, value=cached)

        if isinstance(inp, DateInput):
            return DateField(parent, label=inp.label, default=inp.default)

        if isinstance(inp, SecretInput):
            return SecretField(
                parent,
                label=inp.label,
                pattern=inp.pattern,
                remember_key=inp.remember_key,
            )

        if isinstance(inp, RangeInput):
            return self._build_range_widget(parent, inp, tool)

        # Fallback (should never happen with a well-typed InputSpec)
        return TextField(parent, label=getattr(inp, "label", str(inp)))

    def _build_range_widget(self, parent: tk.Widget, inp: RangeInput, tool: BaseTool) -> tk.Frame:
        """Build a labelled ttk.Scale (slider) widget for a RangeInput InputSpec.

        Layout: label row | [min%] slider [max%]  [ value ] %  hint-text

        When ``inp.numeric_box`` is False (default) the value display is a read-only
        Label (e.g. "101 %").  When True two separate DoubleVars are used:

        * ``actual_var`` — the user-facing value; accepts any value > 0 (no upper
          cap). This is what ``_input_cache`` stores and ``run()`` sees.
        * ``slider_var`` — drives the ttk.Scale knob, clamped to
          ``[min_value, max_value]``. When the user types a value outside the
          slider range the knob snaps to the nearest endpoint, giving a visual
          "at maximum" cue without capping the typed value.

        Entry validation (FocusOut / Return):
          * Non-numeric → revert to previous actual value.
          * <= 0 → revert to previous actual value.
          * Any value > 0 → accepted; actual_var updated; slider_var clamped.

        When ``inp.live`` is True, ``tool.preview_update(key, value)`` is called
        debounced at ~100 ms whenever ``actual_var`` changes.  The value passed
        is the **actual** (unclamped) value.

        Visual layout when ``numeric_box=True``:
            Over-budget threshold
              100%  ━━━━━●━━━━━━━━━━━━  120%      [ 101 ] %   Type any value > 0 …
        """
        tid = tool.id

        # Ensure debounce dict entry exists for this tool.
        if tid not in self._range_debounce:
            self._range_debounce[tid] = {}
        self._range_debounce[tid].setdefault(inp.key, None)

        # Seed input cache with the default value if nothing cached yet.
        cached = self._input_cache[tid].get(inp.key)
        if cached is None:
            self._input_cache[tid][inp.key] = inp.default
            initial = inp.default
        else:
            try:
                initial = float(cached)
            except (TypeError, ValueError):
                initial = inp.default

        container = tk.Frame(parent, bg=tokens.BG_MUTED)

        # Row 1: label
        # When numeric_box=True, the label is a live StringVar that appends the
        # current value (e.g. "Over-budget threshold: 101%") so the user always
        # sees the active value without having to look at the entry on the right.
        # When numeric_box=False, it is a plain static label.  (Fix 1 — Round 13)
        import tkinter.font as _tkfont  # noqa: PLC0415

        _label_var: tk.StringVar | None = None
        _label_font = _tkfont.Font(family="Segoe UI", size=tokens.FS_13)
        # Decimal count for percentage formatting: 0 for step >= 1, else 1.
        # Defined unconditionally so the _on_actual_change closure can capture it
        # without a potential-unbound-variable warning from mypy --strict.
        _step_decimals: int = 0 if inp.step >= 1.0 else 1
        if inp.numeric_box:
            _initial_label = f"{inp.label}: {initial:.{_step_decimals}f}%"
            _label_var = tk.StringVar(value=_initial_label)
            lbl = tk.Label(
                container,
                textvariable=_label_var,
                bg=tokens.BG_MUTED,
                fg=tokens.FG_1,
                font=_label_font,
                anchor="w",
            )
        else:
            lbl = tk.Label(
                container,
                text=inp.label,
                bg=tokens.BG_MUTED,
                fg=tokens.FG_1,
                font=_label_font,
                anchor="w",
            )
        lbl.pack(fill="x")

        # Row 2: [min%] slider [max%]  [ value ] %  hint
        row2 = tk.Frame(container, bg=tokens.BG_MUTED)
        row2.pack(fill="x", pady=(tokens.SP_1, 0))

        # Determine display format from step size.
        _fmt = ":.0f" if inp.step >= 1.0 else ":.1f"

        def _fmt_num(v: float) -> str:
            return format(v, _fmt[1:])

        def _fmt_val(v: float) -> str:
            return _fmt_num(v) + " %"

        def _clamp(v: float) -> float:
            return max(inp.min_value, min(inp.max_value, v))

        # Value display — label (default) or numeric entry (when numeric_box=True).
        _value_lbl: tk.Label | None = None
        _num_entry: tk.Entry | None = None
        _num_entry_var: tk.StringVar | None = None
        _actual_var: tk.DoubleVar | None = None

        if inp.numeric_box:
            # -----------------------------------------------------------------
            # Decoupled-var path (numeric_box=True)
            # actual_var: user-facing, any value > 0 (no upper cap)
            # slider_var: drives the Scale knob, always clamped to [min, max]
            # -----------------------------------------------------------------
            actual_var = tk.DoubleVar(value=initial)
            slider_var = tk.DoubleVar(value=_clamp(initial))
            _actual_var = actual_var

            # Slider → actual (slider always emits clamped values, so just forward)
            def _on_slider_change(*_args: object) -> None:
                v = slider_var.get()
                if inp.step and inp.step > 0:
                    v = round(v / inp.step) * inp.step
                current_actual = actual_var.get()
                if abs(v - current_actual) > 1e-9:
                    actual_var.set(v)

            slider_var.trace_add("write", _on_slider_change)

            # actual_var → update row-1 label (live value display — Fix 1 Round 13)
            #           → update entry display (if entry doesn't have focus)
            #           → update input cache
            #           → fire debounced preview
            def _on_actual_change(*_args: object) -> None:
                v = actual_var.get()
                # Update the row-1 label to show the current value next to the
                # label text (cheap — StringVar.set() does not trigger layout).
                if _label_var is not None:
                    try:
                        _label_var.set(f"{inp.label}: {v:.{_step_decimals}f}%")
                    except Exception:
                        pass
                # Update entry text only when the entry isn't being typed into
                try:
                    if (
                        _num_entry is not None
                        and _num_entry_var is not None
                        and _num_entry.focus_get() is not _num_entry
                    ):
                        _num_entry_var.set(_fmt_num(v))
                except Exception:
                    pass
                # Keep input cache in sync with the actual (unclamped) value
                self._input_cache[tid][inp.key] = v

                if not inp.live:
                    return

                # Debounce preview fire on actual_var value
                pending = self._range_debounce[tid].get(inp.key)
                if pending is not None:
                    try:
                        self._root.after_cancel(pending)
                    except Exception:
                        pass

                def _fire_preview(fire_v: float = v) -> None:
                    self._range_debounce[tid][inp.key] = None
                    result = tool.preview_update(inp.key, fire_v)
                    if result is not None:
                        self._render_result(tid, result)

                after_id = self._root.after(100, _fire_preview)
                self._range_debounce[tid][inp.key] = after_id

            actual_var.trace_add("write", _on_actual_change)

            # ---- range label left ----
            _range_lbl_min = tk.Label(
                row2,
                text=_fmt_num(inp.min_value) + "%",
                bg=tokens.BG_MUTED,
                fg=tokens.FG_3,
                font=_tkfont.Font(family=tokens.FONT_MONO_FALLBACK, size=tokens.FS_12),
            )
            _range_lbl_min.pack(side="left", padx=(0, tokens.SP_1))

            scale = ttk.Scale(
                row2,
                from_=inp.min_value,
                to=inp.max_value,
                orient="horizontal",
                variable=slider_var,
            )
            scale.pack(side="left", fill="x", expand=False, ipadx=0)
            # Cap slider width so it doesn't stretch the full row width.
            scale.configure(length=260)

            # ---- range label right ----
            _range_lbl_max = tk.Label(
                row2,
                text=_fmt_num(inp.max_value) + "%",
                bg=tokens.BG_MUTED,
                fg=tokens.FG_3,
                font=_tkfont.Font(family=tokens.FONT_MONO_FALLBACK, size=tokens.FS_12),
            )
            _range_lbl_max.pack(side="left", padx=(tokens.SP_1, tokens.SP_3))

            # ---- number entry ----
            _num_entry_var = tk.StringVar(value=_fmt_num(initial))
            _num_entry = tk.Entry(
                row2,
                textvariable=_num_entry_var,
                width=6,
                fg=tokens.FG_1,
                font=_tkfont.Font(family="Segoe UI", size=tokens.FS_12),
                relief="sunken",
                bd=1,
                justify="right",
            )
            _num_entry.pack(side="left", padx=(0, tokens.SP_1))

            # ---- % suffix label ----
            _pct_lbl = tk.Label(
                row2,
                text="%",
                bg=tokens.BG_MUTED,
                fg=tokens.FG_2,
                font=_tkfont.Font(family="Segoe UI", size=tokens.FS_12),
            )
            _pct_lbl.pack(side="left", padx=(0, tokens.SP_2))

            # ---- hint text ----
            _hint_min = _fmt_num(inp.min_value)
            _hint_max = _fmt_num(inp.max_value)
            _hint_lbl = tk.Label(
                row2,
                text=f"Type any value > 0 — drag limited to {_hint_min}–{_hint_max}%",
                bg=tokens.BG_MUTED,
                fg=tokens.FG_3,
                font=_tkfont.Font(family="Segoe UI", size=tokens.FS_12, slant="italic"),
            )
            _hint_lbl.pack(side="left", padx=(0, 0))

            # Track the last committed value so invalid input can be reverted.
            _last_committed: list[float] = [initial]

            def _commit_entry(*_args: object) -> None:
                """Validate and commit the typed value.

                Accepts any value > 0 — no upper cap.
                Rejects non-numeric input and values <= 0 (reverts to last good).
                Updates actual_var (which propagates to cache + preview).
                Updates slider_var to clamp(typed, min, max) for knob position.
                """
                assert _num_entry_var is not None  # narrowing for mypy
                text = _num_entry_var.get().strip()
                try:
                    parsed = float(text)
                except ValueError:
                    _num_entry_var.set(_fmt_num(_last_committed[0]))
                    return
                if parsed <= 0:
                    _num_entry_var.set(_fmt_num(_last_committed[0]))
                    return
                _last_committed[0] = parsed
                _num_entry_var.set(_fmt_num(parsed))
                # Update slider knob (clamped) without triggering actual_var feedback
                slider_var.set(_clamp(parsed))
                # Update actual_var to the unclamped typed value
                actual_var.set(parsed)

            _num_entry.bind("<FocusOut>", _commit_entry)
            _num_entry.bind("<Return>", _commit_entry)

            # Use slider_var as the Scale-facing var; expose actual_var as _scale_var
            # (the run() path reads _input_cache, not _scale_var directly,
            # but tests may inspect _scale_var — point it to actual_var so
            # tests that check "what value will run() see" read the right thing).
            _scale_var_exposed = actual_var

        else:
            # -----------------------------------------------------------------
            # Simple single-var path (numeric_box=False) — unchanged behaviour
            # -----------------------------------------------------------------
            scale_var = tk.DoubleVar(value=initial)
            _scale_var_exposed = scale_var

            def _on_scale_change(*_args: object) -> None:
                raw = scale_var.get()
                if inp.step and inp.step > 0:
                    snapped = round(raw / inp.step) * inp.step
                else:
                    snapped = raw
                _value_lbl.configure(text=_fmt_val(snapped))  # type: ignore[union-attr]
                self._input_cache[tid][inp.key] = snapped

                if not inp.live:
                    return

                pending = self._range_debounce[tid].get(inp.key)
                if pending is not None:
                    try:
                        self._root.after_cancel(pending)
                    except Exception:
                        pass

                def _fire_preview(v: float = snapped) -> None:
                    self._range_debounce[tid][inp.key] = None
                    result = tool.preview_update(inp.key, v)
                    if result is not None:
                        self._render_result(tid, result)

                after_id = self._root.after(100, _fire_preview)
                self._range_debounce[tid][inp.key] = after_id

            scale = ttk.Scale(
                row2,
                from_=inp.min_value,
                to=inp.max_value,
                orient="horizontal",
                variable=scale_var,
            )
            scale.pack(side="left", fill="x", expand=True)

            _value_lbl = tk.Label(
                row2,
                text=_fmt_val(initial),
                bg=tokens.BG_MUTED,
                fg=tokens.FG_2,
                font=_tkfont.Font(family="Segoe UI", size=tokens.FS_12),
                width=8,
                anchor="w",
            )
            _value_lbl.pack(side="right", padx=(tokens.SP_2, 0))

            scale_var.trace_add("write", _on_scale_change)

        # Store the scale widget itself so _set_inputs_state can disable it.
        container._scale = scale  # type: ignore[attr-defined]
        # _scale_var exposed to tests: actual_var (numeric_box) or scale_var (plain).
        container._scale_var = _scale_var_exposed  # type: ignore[attr-defined]
        # Keep _value_lbl for backward compat with existing tests (None when numeric_box=True).
        container._value_lbl = _value_lbl  # type: ignore[attr-defined]
        # Expose numeric entry for tests / state management.
        container._num_entry = _num_entry  # type: ignore[attr-defined]
        container._num_entry_var = _num_entry_var  # type: ignore[attr-defined]
        # Expose actual_var for decoupled-var tests (None when numeric_box=False).
        container._actual_var = _actual_var  # type: ignore[attr-defined]

        return container

    # -----------------------------------------------------------------------
    # Tool activation
    # -----------------------------------------------------------------------

    def _activate_tool(self, tool_id: str) -> None:
        if tool_id not in self._tool_frames:
            return

        self._active_id = tool_id
        tool = self._tool_map[tool_id]

        # Update rail selection styling
        for tid, lbl in self._rail_items.items():
            if tid == tool_id:
                lbl.configure(bg=tokens.RAIL_SELECTED, fg=tokens.FG_INVERSE)
            else:
                lbl.configure(bg=tokens.BG_PANEL, fg=tokens.FG_1)

        # Update root window title
        self._root.title(f"{APP_TITLE} — {tool.label}")

        # Update in-app header: chip reflects active tool's short mark + title text
        self._header_chip.configure(text=tool.short)
        self._header_title_var.set(f"{APP_TITLE} — {tool.label}")

        # Licence gate — check before lifting the tool frame
        feature = getattr(tool, "requires_feature", None)
        if feature is not None:
            import toolkit.licence as _licence  # noqa: PLC0415  (lazy import)

            status = _licence.read_status()
            if status.state not in {"active", "grace"}:
                self._show_unlock_cta(tool)
                self._set_status("Ready")
                logger.info("Licence gate blocked tool: %s (%s)", tool.label, tool_id)
                return
            if status.state == "grace":
                logger.warning(
                    "Licence in grace period — allowing tool: %s (%s)",
                    tool.label,
                    tool_id,
                )

        # Show/hide content frames — use place_forget/place instead of lower/lift
        # so that inactive frames are fully removed from the geometry manager.
        # Placed frames with relwidth/relheight receive <Configure> from Tk even
        # when hidden (lowered), multiplying resize work by the tool count.
        # (Fix 2 — Round 13)
        for tid, frame in self._tool_frames.items():
            if tid != tool_id:
                frame.place_forget()
        if self._unlock_frame is not None:
            self._unlock_frame.place_forget()
        if self._user_frame is not None:
            self._user_frame.place_forget()
        self._tool_frames[tool_id].place(
            in_=self._content_outer, x=0, y=0, relwidth=1.0, relheight=1.0
        )

        self._set_status("Ready")
        logger.info("Activated tool: %s (%s)", tool.label, tool_id)

    def _show_unlock_cta(self, tool: BaseTool) -> None:
        """Render the unlock CTA frame in place of the tool's content frame."""
        # Remove all tool content frames from the geometry manager (Fix 2 — Round 13)
        for frame in self._tool_frames.values():
            frame.place_forget()
        if self._user_frame is not None:
            self._user_frame.place_forget()

        # Build the unlock frame lazily
        if self._unlock_frame is None:
            self._unlock_frame = tk.Frame(self._content_outer, bg=tokens.BG_MUTED)

            pad = tokens.SP_4

            self._unlock_title_var = tk.StringVar(value=tool.label)

            hdr_frame = tk.Frame(self._unlock_frame, bg=tokens.BG_MUTED)
            hdr_frame.pack(fill="x", padx=pad, pady=(pad, 0))

            import tkinter.font as _tkfont  # noqa: PLC0415

            tk.Label(
                hdr_frame,
                textvariable=self._unlock_title_var,
                font=_tkfont.Font(family=self._fonts.sans_family, size=tokens.FS_16, weight="bold"),
                fg=tokens.FG_1,
                bg=tokens.BG_MUTED,
                anchor="w",
            ).pack(fill="x")
            tk.Label(
                hdr_frame,
                text="This tool requires an active licence.",
                font=_tkfont.Font(family=self._fonts.sans_family, size=tokens.FS_13),
                fg=tokens.FG_MUTED,
                bg=tokens.BG_MUTED,
                anchor="w",
                wraplength=820,
                justify="left",
            ).pack(fill="x", pady=(tokens.SP_1, 0))

            banner_frame = tk.Frame(self._unlock_frame, bg=tokens.BG_MUTED)
            banner_frame.pack(fill="x", padx=pad, pady=(tokens.SP_GAP_SECTION, 0))
            Banner(
                banner_frame,
                level="info",
                text=(
                    "Get started with School Tool Pro in three steps: "
                    "1. Sign in  ·  2. Generate an annual invoice  ·  "
                    "3. Upload your Purchase Order. "
                    "Your tool unlocks as soon as your PO is validated."
                ),
            ).pack(fill="x")

            # Instant-validation note for Compass / CASES21 POs.
            note_frame = tk.Frame(self._unlock_frame, bg=tokens.BG_MUTED)
            note_frame.pack(fill="x", padx=pad, pady=(tokens.SP_GAP_SECTION, 0))
            Banner(
                note_frame,
                level="ok",
                text=(
                    "Purchase Orders exported directly from Compass or CASES21 "
                    "are validated instantly by the system — no waiting for "
                    "manual review. Scanned or non-standard POs are reviewed "
                    "within one business day."
                ),
            ).pack(fill="x")

            btn_frame = tk.Frame(self._unlock_frame, bg=tokens.BG_MUTED)
            btn_frame.pack(fill="x", padx=pad, pady=(tokens.SP_GAP_SECTION, 0))

            ttk.Button(
                btn_frame,
                text="Go to User tab",
                style="Accent.TButton",
                command=self._activate_user_tab,
            ).pack(side="left", padx=(0, tokens.SP_2))

            ttk.Button(
                btn_frame,
                text="How to save a CASES21 PO",
                command=self._show_cases21_po_help,
            ).pack(side="left", padx=(0, tokens.SP_2))

            tk.Label(
                btn_frame,
                text="Already paid? Try “Refresh licence” in User → Service.",
                fg=tokens.FG_MUTED,
                bg=tokens.BG_MUTED,
                font=self._small_font(),
                anchor="w",
            ).pack(side="left")
        else:
            # Update the title for whichever paid tool was clicked
            if self._unlock_title_var is not None:
                self._unlock_title_var.set(tool.label)

        # Place (or re-place) the unlock frame as the sole visible content
        self._unlock_frame.place(in_=self._content_outer, x=0, y=0, relwidth=1.0, relheight=1.0)

    def _show_cases21_po_help(self) -> None:
        """Open a scrollable dialog with step-by-step instructions for saving
        a Purchase Order out of CASES21 as a PDF ready to upload."""
        title = "How to save a CASES21 Purchase Order"
        body = _CASES21_PO_HELP_TEXT
        self._show_help_window(title, body)

    # -----------------------------------------------------------------------
    # Rail hover effects
    # -----------------------------------------------------------------------

    def _rail_hover(self, widget: tk.Label, tool_id: str) -> None:
        if tool_id != self._active_id:
            widget.configure(bg=tokens.BG_RAIL_HOVER)

    def _rail_unhover(self, widget: tk.Label, tool_id: str) -> None:
        if tool_id == self._active_id:
            widget.configure(bg=tokens.RAIL_SELECTED, fg=tokens.FG_INVERSE)
        else:
            widget.configure(bg=tokens.BG_PANEL, fg=tokens.FG_1)

    # -----------------------------------------------------------------------
    # Static rail entries
    # -----------------------------------------------------------------------

    def _show_instructions(self) -> None:
        """Open a scrollable window showing the active tool's built-in help text.

        Tools expose their help via a ``help_text`` class attribute. If the
        active tool doesn't define one, a friendly fallback is shown.
        """
        tool = self._tool_map.get(self._active_id)
        help_text: str | None = getattr(tool, "help_text", None) if tool else None
        title = f"{tool.label} — Instructions" if tool else "Instructions"

        if not help_text:
            messagebox.showinfo(
                "Instructions",
                "No instructions have been written for this tool yet.\n\n"
                f"If you'd like documentation here, email {SUPPORT_EMAIL}.",
            )
            return

        self._show_help_window(title, help_text)

    def _show_help_window(self, title: str, help_text: str) -> None:
        """Render ``help_text`` in a dedicated scrollable modal window with a
        navy header strip, heading/mono tagging, and live colour swatches for
        any ``#RRGGBB`` hex codes in the body.
        """
        # Build a dedicated modal window with a scrollable read-only Text widget.
        win = tk.Toplevel(self._root)
        win.title(title)
        win.geometry("720x640")
        win.minsize(560, 400)
        win.transient(self._root)
        win.configure(bg=tokens.BG_PANEL)

        # Header strip (navy band with the tool label)
        header = tk.Frame(win, bg=tokens.BRAND_NAVY, height=48)
        header.pack(side="top", fill="x")
        header.pack_propagate(False)
        tk.Label(
            header,
            text=title,
            bg=tokens.BRAND_NAVY,
            fg=tokens.FG_INVERSE,
            font=tkfont.Font(family=self._fonts.sans_family, size=tokens.FS_14, weight="bold"),
            anchor="w",
            padx=tokens.SP_4,
        ).pack(fill="both", expand=True)

        # Body: scrollable Text
        body = tk.Frame(win, bg=tokens.BG_PANEL)
        body.pack(side="top", fill="both", expand=True, padx=tokens.SP_4, pady=tokens.SP_3)

        yscroll = ttk.Scrollbar(body, orient="vertical")
        yscroll.pack(side="right", fill="y")

        text = tk.Text(
            body,
            wrap="word",
            bg=tokens.BG_PANEL,
            fg=tokens.FG_1,
            relief="flat",
            borderwidth=0,
            padx=tokens.SP_3,
            pady=tokens.SP_3,
            font=tkfont.Font(family=self._fonts.sans_family, size=tokens.FS_13),
            yscrollcommand=yscroll.set,
        )
        yscroll.configure(command=text.yview)
        text.pack(side="left", fill="both", expand=True)

        # Tag configuration for emphasis
        text.tag_configure(
            "heading",
            font=tkfont.Font(family=self._fonts.sans_family, size=tokens.FS_14, weight="bold"),
            foreground=tokens.BRAND_NAVY,
            spacing1=12,
            spacing3=4,
        )
        text.tag_configure(
            "mono",
            font=tkfont.Font(family=self._fonts.mono_family, size=tokens.FS_13),
        )

        # Any "#RRGGBB" hex code in the body gets a live colour swatch
        # embedded inline (so the reader sees the actual colour, not just
        # the code).
        import re as _re

        hex_re = _re.compile(r"#[0-9A-Fa-f]{6}\b")

        def _insert_line_with_swatches(raw_line: str, tag: str | None) -> None:
            """Insert ``raw_line`` into the Text widget. Every ``#RRGGBB`` hex
            code is **replaced** by a small colour rectangle (the user sees the
            actual colour, not the code)."""
            pos = 0
            for match in hex_re.finditer(raw_line):
                start, end = match.span()
                if start > pos:
                    segment = raw_line[pos:start]
                    if tag:
                        text.insert("end", segment, tag)
                    else:
                        text.insert("end", segment)
                hex_code = match.group(0).upper()
                # Small 14x12 swatch with a subtle 1 px border.
                swatch = tk.Frame(
                    text,
                    bg=hex_code,
                    width=14,
                    height=12,
                    highlightthickness=1,
                    highlightbackground=tokens.BORDER_SUBTLE,
                )
                swatch.pack_propagate(False)
                text.window_create("end", window=swatch, padx=0, pady=0)
                # Hex code itself is intentionally NOT inserted — the swatch
                # alone communicates the colour; showing raw codes clutters
                # the prose.
                pos = end
            tail = raw_line[pos:] + "\n"
            if tag:
                text.insert("end", tail, tag)
            else:
                text.insert("end", tail)

        # Lines in ALL-CAPS are treated as headings; indented lines (4 spaces)
        # are treated as monospace blocks.
        for line in help_text.splitlines():
            stripped = line.strip()
            is_heading = (
                bool(stripped)
                and stripped == stripped.upper()
                and any(c.isalpha() for c in stripped)
                and len(stripped) > 2
            )
            is_mono = line.startswith("    ")
            if is_heading:
                _insert_line_with_swatches(line, "heading")
            elif is_mono:
                _insert_line_with_swatches(line, "mono")
            else:
                _insert_line_with_swatches(line, None)

        text.configure(state="disabled")  # read-only

        # Footer: Close button
        footer = tk.Frame(win, bg=tokens.BG_PANEL)
        footer.pack(side="bottom", fill="x", padx=tokens.SP_4, pady=tokens.SP_3)
        ttk.Button(footer, text="Close", command=win.destroy).pack(side="right")

        # Centre on the main window, modal-style focus
        win.update_idletasks()
        x = self._root.winfo_rootx() + (self._root.winfo_width() - win.winfo_width()) // 2
        y = self._root.winfo_rooty() + (self._root.winfo_height() - win.winfo_height()) // 2
        win.geometry(f"+{max(x, 0)}+{max(y, 0)}")
        win.grab_set()
        win.focus_set()

    def _make_press_hold_button(
        self,
        parent: tk.Widget,
        label: str,
        get_text: Callable[[], str],
    ) -> None:
        """Pack a button + sibling label that reveals text only while held.

        Pattern: while the user holds the left mouse button on the button,
        the sibling label displays ``get_text()``.  When the button is
        released or the pointer leaves the button, the label clears.

        Used by HYIA so the user can verify the calculation formula
        without exposing the masked SIN to anyone glancing at the screen.
        """
        # Reveal label sits to the right of the button.  fg uses the muted
        # token so it's clearly secondary; mono font keeps numeric digits
        # aligned for verification.
        reveal_var = tk.StringVar(value="")
        reveal_lbl = tk.Label(
            parent,
            textvariable=reveal_var,
            fg=tokens.FG_2,
            bg=tokens.BG_MUTED,
            font=tkfont.Font(family=self._fonts.mono_family, size=tokens.FS_13),
            anchor="w",
        )
        # Pack the button first, then the label, so the label flows to the
        # right of the button in the existing left-to-right action row.
        btn = ttk.Button(parent, text=label)
        btn.pack(side="left", padx=(0, tokens.SP_1))
        reveal_lbl.pack(side="left", padx=(tokens.SP_2, 0))

        def _on_press(_e: object, _v: tk.StringVar = reveal_var) -> None:
            try:
                _v.set(get_text())
            except Exception as exc:  # noqa: BLE001 — defensive, never propagate
                logger.debug("press_hold reveal callable failed: %s", exc)
                _v.set("")

        def _on_release(_e: object, _v: tk.StringVar = reveal_var) -> None:
            _v.set("")

        btn.bind("<ButtonPress-1>", _on_press)
        btn.bind("<ButtonRelease-1>", _on_release)
        # Also clear when the pointer leaves the button — covers the edge
        # case where the user drags off before releasing.
        btn.bind("<Leave>", _on_release)

    def _show_about(self) -> None:
        # Kept for backward compatibility with any tests / call sites that
        # still reference it; the rail itself now exposes Privacy Policy
        # instead of About (Round 21).
        messagebox.showinfo(
            "About",
            f"{APP_TITLE}\nSupport: {SUPPORT_EMAIL}",
        )

    def _show_privacy_policy(self) -> None:
        """Open the Privacy Policy in a scrollable modal.

        Loads the canonical text from ``docs/store_privacy_policy.md``.
        We strip the leading single ``#`` heading because the help-window
        already shows the title in the navy header strip.
        """
        from pathlib import Path as _Path

        # Locate the policy file relative to the package root. When the app
        # is packaged as an MSIX the docs/ folder ships next to toolkit/
        # under the same install root, so this relative-from-this-file walk
        # resolves correctly in both dev and packaged builds.
        here = _Path(__file__).resolve().parent.parent
        policy_path = here / "docs" / "store_privacy_policy.md"
        try:
            raw = policy_path.read_text(encoding="utf-8")
        except OSError:
            messagebox.showinfo(
                "Privacy Policy",
                f"Could not locate the privacy policy file.\n\n"
                f"Please email {SUPPORT_EMAIL} for a copy.",
            )
            return

        # Strip a leading "# Heading" line if present — the help-window
        # already renders a navy title bar so the duplicate is noisy.
        lines = raw.splitlines()
        if lines and lines[0].lstrip().startswith("# "):
            lines = lines[1:]
            # Also strip the immediate blank line that usually follows.
            if lines and not lines[0].strip():
                lines = lines[1:]
        body = "\n".join(lines)

        self._show_help_window("Privacy Policy", body)

    def _show_user(self) -> None:
        self._activate_user_tab()

    def _activate_user_tab(self) -> None:
        """Place the UserFrame as the sole visible content (built lazily)."""
        if self._user_frame is None:
            self._user_frame = UserFrame(
                self._content_outer,
                fonts=self._fonts,
            )

        # Remove all other frames from the geometry manager (Fix 2 — Round 13)
        for frame in self._tool_frames.values():
            frame.place_forget()
        if self._unlock_frame is not None:
            self._unlock_frame.place_forget()
        self._user_frame.place(in_=self._content_outer, x=0, y=0, relwidth=1.0, relheight=1.0)

        # Update title and SF chip
        self._root.title(f"{APP_TITLE} — User")
        self._header_chip.configure(text="US")
        self._header_title_var.set(f"{APP_TITLE} — User")

        # De-select any highlighted tool in the rail
        for lbl in self._rail_items.values():
            lbl.configure(bg=tokens.BG_PANEL, fg=tokens.FG_1)

        self._set_status("Ready")
        self._user_frame.refresh()
        logger.info("Activated User tab")

    # -----------------------------------------------------------------------
    # Status bar
    # -----------------------------------------------------------------------

    def _set_status(self, message: str) -> None:
        self._status_left_var.set(message)

    # -----------------------------------------------------------------------
    # Tool runner
    # -----------------------------------------------------------------------

    def _run_tool(self, tool: BaseTool) -> None:
        tid = tool.id

        # Gather input values from widgets
        wmap = self._tool_widgets[tid]
        resolved: dict[str, Any] = {}

        for inp in tool.inputs:
            w = wmap.get(inp.key)
            if w is None:
                continue
            if isinstance(inp, FileInput) and isinstance(w, FileRow):
                p = w.get_path()
                if p:
                    resolved[inp.key] = p
                    self._input_cache[tid][inp.key] = p
            elif isinstance(inp, TextInput) and isinstance(w, TextField):
                resolved[inp.key] = w.get()
                self._input_cache[tid][inp.key] = w.get()
            elif isinstance(inp, NumberInput) and isinstance(w, NumberField):
                from decimal import Decimal

                raw = w.get()
                try:
                    resolved[inp.key] = Decimal(raw) if inp.decimals else int(raw)
                except Exception:
                    resolved[inp.key] = raw
                self._input_cache[tid][inp.key] = raw
            elif isinstance(inp, CurrencyInput) and isinstance(w, CurrencyField):
                from decimal import Decimal

                raw = w.get()
                try:
                    resolved[inp.key] = Decimal(raw)
                except Exception:
                    resolved[inp.key] = Decimal("0")
                self._input_cache[tid][inp.key] = raw
            elif isinstance(inp, DateInput) and isinstance(w, DateField):
                resolved[inp.key] = w.get_date()
                self._input_cache[tid][inp.key] = w.get_date()
            elif isinstance(inp, SecretInput) and isinstance(w, SecretField):
                resolved[inp.key] = w.get()
            elif isinstance(inp, RangeInput):
                # Value is always kept current in input_cache by the slider trace.
                cached_range = self._input_cache[tid].get(inp.key, inp.default)
                try:
                    resolved[inp.key] = float(cached_range)
                except (TypeError, ValueError):
                    resolved[inp.key] = inp.default
                self._input_cache[tid][inp.key] = resolved[inp.key]

        # Add output path if present
        out_row = self._tool_output_rows.get(tid)
        if out_row and tool.output:
            out_path = out_row.get_path()
            if out_path:
                resolved[tool.output.key] = out_path

        # Disable inputs + show progress bar
        self._set_inputs_state(tid, "disabled")
        pb_frame = wmap.get("__pb_frame__")
        if pb_frame:
            pb_frame.pack(fill="x", padx=tokens.SP_4, pady=(tokens.SP_2, 0))
        pb = self._tool_progress.get(tid)
        if pb:
            pb.set(0, "Starting…")

        # Clear previous results
        self._clear_results(tid)

        self._set_status("Running…")
        logger.info("Starting tool: %s", tool.label)

        executor = self._executors[tid]

        def _progress_worker(pct: int, msg: str) -> None:
            self._root.after(0, lambda: self._on_progress(tid, pct, msg))

        def _worker() -> ToolResult:
            return tool.run(resolved, _progress_worker)

        future: Future[ToolResult] = executor.submit(_worker)
        future.add_done_callback(
            lambda f: self._root.after(0, lambda: self._on_tool_complete(tid, f))
        )

    def _on_progress(self, tid: str, pct: int, msg: str) -> None:
        if tid != self._active_id:
            return
        pb = self._tool_progress.get(tid)
        if pb:
            pb.set(pct, msg)
        self._set_status(msg)

    def _on_tool_complete(self, tid: str, future: Future[ToolResult]) -> None:
        # Re-enable inputs
        self._set_inputs_state(tid, "normal")

        exc = future.exception()
        if exc is not None:
            logger.exception("Tool %s raised an exception", tid, exc_info=exc)
            # Round 20 — translate uncaught exceptions to plain English so
            # users see something actionable instead of a Python type name.
            from toolkit.user_errors import friendly_error

            fe = friendly_error(exc) if isinstance(exc, Exception) else None
            if fe is not None:
                from toolkit.base_tool import LogLine

                result = ToolResult(
                    status="error",
                    banner_level="danger",
                    banner_text=fe.banner,
                    log_lines=[
                        LogLine("WHAT WENT WRONG", tag="heading"),
                        LogLine(fe.message, tag="danger"),
                        LogLine("HOW TO FIX IT", tag="heading"),
                        LogLine(fe.advice, tag="muted"),
                        LogLine("TECHNICAL DETAIL (for support)", tag="heading"),
                        LogLine(fe.technical, tag="muted"),
                    ],
                )
            else:
                result = ToolResult(
                    status="error",
                    banner_level="danger",
                    banner_text="Something unexpected went wrong.",
                )
        else:
            result = future.result()

        self._render_result(tid, result)

        # Hide progress bar
        wmap = self._tool_widgets[tid]
        pb_frame = wmap.get("__pb_frame__")
        if pb_frame:
            pb_frame.pack_forget()
        pb = self._tool_progress.get(tid)
        if pb:
            pb.set(100, result.banner_text[:80])

        self._set_status(result.banner_text[:100])
        logger.info("Tool %s completed with status %s", tid, result.status)

    def _render_result(self, tid: str, result: ToolResult) -> None:
        wmap = self._tool_widgets[tid]
        banner_frame = wmap.get("__banner_frame__")

        # Banner
        if banner_frame:
            for child in banner_frame.winfo_children():
                child.destroy()
            banner = Banner(banner_frame, level=result.banner_level, text=result.banner_text)
            banner.pack(fill="x")
            self._tool_banners[tid] = banner

        # Metrics
        metric_frame = self._tool_metric_frames.get(tid)
        if metric_frame:
            for child in metric_frame.winfo_children():
                child.destroy()
            if result.metrics:
                large_single = len(result.metrics) == 1
                metric_frame.pack(fill="x", padx=tokens.SP_4, pady=(tokens.SP_2, 0))
                row = tk.Frame(metric_frame, bg=tokens.BG_MUTED)
                row.pack(fill="x")
                for lbl, val, tone in result.metrics:
                    m = Metric(
                        row,
                        label=lbl,
                        value=val,
                        tone=tone or "neutral",
                        large=large_single,
                    )
                    m.pack(side="left", padx=(0, tokens.SP_3), expand=True)

        # Log lines
        lv = self._tool_logviews.get(tid)
        log_frame = wmap.get("__log_frame__")
        if lv and result.log_lines:
            lv.clear()
            for line in result.log_lines:
                lv.append(line)
            if log_frame:
                log_frame.pack(fill="both", expand=True, padx=tokens.SP_4, pady=(tokens.SP_2, 0))

        # Reset filter state when a fresh ToolResult arrives
        self._tool_filter[tid] = None
        self._tool_table_specs[tid] = None
        self._tool_rails[tid] = None
        # Hide any stale chip
        chip_frame_ref = wmap.get("__chip_frame__")
        if chip_frame_ref is not None:
            for child in chip_frame_ref.winfo_children():
                child.destroy()
            chip_frame_ref.pack_forget()

        # Table (and optional side rail)
        table_frame = wmap.get("__table_frame__")
        if table_frame:
            # Determine whether we have any table content to show
            has_table_spec = result.table is not None
            has_legacy_table = result.table_columns is not None and result.table_rows is not None

            if has_table_spec or has_legacy_table:
                # Destroy any previously-rendered content
                for child in table_frame.winfo_children():
                    child.destroy()

                if result.side_rail is not None:
                    # -------------------------------------------------------
                    # Two-column layout: rail (220 px) | table (fill)
                    # -------------------------------------------------------
                    grid_frame = tk.Frame(table_frame, bg=tokens.BG_MUTED)
                    grid_frame.pack(fill="both", expand=True)

                    def _on_rail_select(filter_key: str, tool_id: str = tid) -> None:
                        self._apply_filter(tool_id, filter_key)

                    rail = SelectableList(
                        grid_frame,
                        items=result.side_rail,
                        on_select=_on_rail_select,
                        focus_on_mount=False,
                        width=220,
                    )
                    rail.grid(
                        row=0,
                        column=0,
                        sticky="ns",
                        padx=(0, tokens.SP_GAP_SECTION),
                    )

                    tbl = self._build_table_widget(grid_frame, result)
                    tbl.grid(row=0, column=1, sticky="nsew")

                    grid_frame.grid_columnconfigure(0, weight=0, minsize=220)
                    grid_frame.grid_columnconfigure(1, weight=1)
                    grid_frame.grid_rowconfigure(0, weight=1)

                    # Cache for filter operations
                    self._tool_rails[tid] = rail
                    self._tool_table_specs[tid] = result.table
                else:
                    # -------------------------------------------------------
                    # Single-column layout — preserved from today
                    # -------------------------------------------------------
                    tbl = self._build_table_widget(table_frame, result)
                    tbl.pack(fill="both", expand=True)

                table_frame.pack(fill="both", expand=True, padx=tokens.SP_4, pady=(tokens.SP_2, 0))
                self._tool_tables[tid] = tbl

    def _build_table_widget(self, parent: tk.Widget, result: ToolResult) -> Table:
        """Construct and populate a Table widget from a ToolResult.

        Supports two source paths:
        - ``result.table`` (TableSpec) — new path; forwards row_style and on_row_click.
        - ``result.table_columns`` + ``result.table_rows`` — legacy path; preserved exactly.

        The caller is responsible for placing (pack/grid) the returned widget.
        """
        if result.table is not None:
            spec: TableSpec = result.table
            tbl = Table(
                parent,
                columns=spec.columns,
                row_style=spec.row_style,
                on_row_click=spec.on_row_click,
            )
            tbl.set_rows(spec.rows)
        else:
            # Legacy path — table_columns / table_rows (already guarded by caller)
            cols = result.table_columns or []
            rows = result.table_rows or []
            tbl = Table(parent, columns=cols)
            tbl.set_rows(rows)
        return tbl

    # -----------------------------------------------------------------------
    # Filter helpers (click-to-filter on the in-tool side rail)
    # -----------------------------------------------------------------------

    def _apply_filter(self, tool_id: str, filter_key: str) -> None:
        """Filter the table to rows whose ``_faculty`` equals *filter_key*.

        Called when the user clicks a row in the in-tool SelectableList rail.
        Updates the table widget in place (``Table.set_rows``), highlights the
        active rail row, and shows the filter chip.
        """
        self._tool_filter[tool_id] = filter_key
        spec = self._tool_table_specs.get(tool_id)
        if spec is None:
            return
        filtered_rows = _filter_rows(spec.rows, filter_key)
        table_widget = self._tool_tables.get(tool_id)
        if table_widget is not None:
            table_widget.set_rows(filtered_rows)
        rail = self._tool_rails.get(tool_id)
        if rail is not None:
            rail.set_active(filter_key)
        self._update_filter_chip(tool_id, len(filtered_rows), len(spec.rows))

    def _clear_filter(self, tool_id: str) -> None:
        """Remove any active filter and restore the full row set."""
        self._tool_filter[tool_id] = None
        spec = self._tool_table_specs.get(tool_id)
        if spec is None:
            return
        table_widget = self._tool_tables.get(tool_id)
        if table_widget is not None:
            table_widget.set_rows(spec.rows)
        rail = self._tool_rails.get(tool_id)
        if rail is not None:
            rail.set_active(None)
        self._update_filter_chip(tool_id, 0, 0)

    def _update_filter_chip(self, tool_id: str, shown: int, total: int) -> None:
        """Render or hide the filter chip below the table.

        When *shown* == 0 or *shown* == *total* the chip is hidden (no filter
        active).  Otherwise a one-line label "Showing N of M — clear filter x"
        is shown with a clickable x label that invokes ``_clear_filter``.
        """
        chip_frame = self._tool_filter_chips.get(tool_id)
        if chip_frame is None:
            return
        # Clear previous chip contents
        for w in chip_frame.winfo_children():
            w.destroy()
        if shown == 0 or shown == total:
            chip_frame.pack_forget()
            return
        chip_frame.pack(fill="x", padx=tokens.SP_4, pady=(tokens.SP_1, 0))
        import tkinter.font as _tkfont  # noqa: PLC0415

        chip_font = _tkfont.Font(family="Segoe UI", size=tokens.FS_12)
        tk.Label(
            chip_frame,
            text=f"Showing {shown} of {total} — clear filter ",
            bg=tokens.BG_MUTED,
            fg=tokens.FG_3,
            font=chip_font,
            anchor="w",
        ).pack(side="left")
        clear_lbl = tk.Label(
            chip_frame,
            text="×",
            bg=tokens.BG_MUTED,
            fg=tokens.FG_2,
            font=chip_font,
            cursor="hand2",
        )
        clear_lbl.pack(side="left")

        def _on_clear_click(_e: Any, tid: str = tool_id) -> None:
            self._clear_filter(tid)

        clear_lbl.bind("<Button-1>", _on_clear_click)

    def _clear_results(self, tid: str) -> None:
        wmap = self._tool_widgets[tid]

        # Clear banner
        banner_frame = wmap.get("__banner_frame__")
        if banner_frame:
            for child in banner_frame.winfo_children():
                child.destroy()
        self._tool_banners[tid] = None

        # Clear metrics
        metric_frame = self._tool_metric_frames.get(tid)
        if metric_frame:
            for child in metric_frame.winfo_children():
                child.destroy()
            metric_frame.pack_forget()

        # Clear log
        lv = self._tool_logviews.get(tid)
        if lv:
            lv.clear()
        log_frame = wmap.get("__log_frame__")
        if log_frame:
            log_frame.pack_forget()

        # Clear table
        table_frame = wmap.get("__table_frame__")
        if table_frame:
            for child in table_frame.winfo_children():
                child.destroy()
            table_frame.pack_forget()
        self._tool_tables[tid] = None

    def _clear_tool(self, tool: BaseTool) -> None:
        """Handle the Clear button click: reset all UI state for the tool,
        then delegate per-tool state to tool.clear().

        UI-level resets handled here:
          1. File picker widget values + input cache cleared.
          2. Banner frame emptied.
          3. Progress bar frame hidden.
          4. Metrics frame hidden and emptied.
          5. Log view cleared and hidden.
          6. Table frame destroyed and hidden.
          7. Primary button re-enabled.
          8. Active filter reset + filter chip hidden.
          9. tool.clear() called for per-tool state.
        """
        tid = tool.id
        wmap = self._tool_widgets[tid]

        # 1. Clear file picker widgets and input cache
        for inp in tool.inputs:
            w = wmap.get(inp.key)
            if w is not None and isinstance(w, FileRow):
                w._var.set("")  # clear the displayed path
        out_row = self._tool_output_rows.get(tid)
        if out_row is not None:
            out_row._var.set("")  # clear the output file path
        self._input_cache[tid] = {}

        # 2. Clear banner
        banner_frame = wmap.get("__banner_frame__")
        if banner_frame:
            for child in banner_frame.winfo_children():
                child.destroy()
        self._tool_banners[tid] = None

        # 3. Hide progress bar
        pb_frame = wmap.get("__pb_frame__")
        if pb_frame:
            pb_frame.pack_forget()
        pb = self._tool_progress.get(tid)
        if pb:
            pb.set(0, "")

        # 4. Hide and empty metrics
        metric_frame = self._tool_metric_frames.get(tid)
        if metric_frame:
            for child in metric_frame.winfo_children():
                child.destroy()
            metric_frame.pack_forget()

        # 5. Clear and hide log
        lv = self._tool_logviews.get(tid)
        if lv:
            lv.clear()
        log_frame = wmap.get("__log_frame__")
        if log_frame:
            log_frame.pack_forget()

        # 6. Reset active filter BEFORE destroying table children.
        #
        # Order matters: the SelectableList (rail) lives inside table_frame's
        # child grid_frame.  If we destroyed table_frame's children first,
        # rail.set_active(None) would fire configure() calls against already-
        # destroyed Tk widgets and raise "invalid command name …" errors.
        # Clearing the rail state here — while the widgets are still alive —
        # prevents that stale-callback error.
        self._tool_filter[tid] = None
        self._tool_table_specs[tid] = None
        rail = self._tool_rails.get(tid)
        if rail is not None:
            # Guard with winfo_exists() in case the widget was destroyed by
            # an earlier pack_forget/GC cycle (belt-and-suspenders).
            try:
                if rail.winfo_exists():
                    rail.set_active(None)
            except tk.TclError:
                pass
        self._tool_rails[tid] = None

        # Destroy table children and hide (safe now — rail state cleared above).
        table_frame = wmap.get("__table_frame__")
        if table_frame:
            for child in table_frame.winfo_children():
                child.destroy()
            table_frame.pack_forget()
        self._tool_tables[tid] = None

        # 7. Re-enable primary button
        primary = self._tool_primary_btns.get(tid)
        if primary:
            primary.configure(state="normal")

        # 8. Hide the filter chip (filter state already cleared above in step 6).
        chip_frame = self._tool_filter_chips.get(tid)
        if chip_frame is not None:
            for child in chip_frame.winfo_children():
                try:
                    child.destroy()
                except tk.TclError:
                    pass
            chip_frame.pack_forget()

        # 9. Delegate per-tool state reset
        tool.clear()

        self._set_status("Ready")
        logger.info("Cleared tool: %s (%s)", tool.label, tid)

    def _set_inputs_state(self, tid: str, state: str) -> None:
        """Enable or disable all input widgets and the primary button for a tool."""
        wmap = self._tool_widgets[tid]
        tool = self._tool_map[tid]

        for inp in tool.inputs:
            w = wmap.get(inp.key)
            if w is None:
                continue
            if isinstance(w, FileRow):
                w.set_state(state)
            elif isinstance(inp, RangeInput):
                # RangeInput renders as a tk.Frame container; the actual
                # ttk.Scale is stored as container._scale.  The optional
                # numeric entry (_num_entry) is disabled alongside it.
                scale_widget = getattr(w, "_scale", None)
                if scale_widget is not None:
                    try:
                        scale_widget.configure(state=state)
                    except tk.TclError:
                        pass
                num_entry = getattr(w, "_num_entry", None)
                if num_entry is not None:
                    try:
                        num_entry.configure(state=state)
                    except tk.TclError:
                        pass
            else:
                try:
                    w.configure(state=state)
                except tk.TclError:
                    pass

        out_row = self._tool_output_rows.get(tid)
        if out_row:
            out_row.set_state(state)

        primary = self._tool_primary_btns.get(tid)
        if primary:
            primary.configure(state=state)

    # -----------------------------------------------------------------------
    # Global exception handler
    # ----------------------------------------------------------------------
    def _handle_tk_exception(
        self,
        exc_type: type[BaseException],
        exc_value: BaseException,
        exc_tb: Any,
    ) -> None:
        tb_str = "".join(traceback.format_exception(exc_type, exc_value, exc_tb))
        logger.error("Unhandled exception in Tk callback:\n%s", tb_str)

        msg = str(exc_value)
        log_hint = f"\nSee log at: {self._log_path}" if self._log_path else ""

        # Show a danger banner in the active tool frame
        if self._active_id and self._active_id in self._tool_widgets:
            wmap = self._tool_widgets[self._active_id]
            banner_frame = wmap.get("__banner_frame__")
            if banner_frame:
                for child in banner_frame.winfo_children():
                    child.destroy()
                banner = Banner(
                    banner_frame,
                    level="danger",
                    text=f"An unexpected error occurred: {msg}{log_hint}",
                )
                banner.pack(fill="x")

    # -----------------------------------------------------------------------
    # Root-window resize debounce + drag-state suspension (Fix 2/Round 13,
    # Fix 5/Round 17)
    # -----------------------------------------------------------------------

    def _on_root_configure(self, _event: Any) -> None:
        """Debounce handler for the root window's <Configure> event.

        Round 13: batches root Configure events into a single deferred call
        ~100 ms after the last event, preventing layout thrash.

        Round 17 (Fix 5): additionally sets ``_drag_active = True`` so that
        canvas Configure handlers (in _build_tool_frame and SelectableList)
        can short-circuit entirely during the drag, skipping even the after()
        scheduling overhead.  ``_on_drag_settled`` runs 150 ms after the last
        event and: (a) clears _drag_active, (b) fires all pending canvas
        configure callbacks once, (c) runs the root settle (no-op today).

        The 150 ms settle window is deliberately longer than the inner canvas
        debounce (100 ms) so it acts as the outer gate.
        """
        # Mark drag as active -- canvas handlers will skip during this window
        self._drag_active = True

        # Cancel-and-reschedule the settle timer
        if self._drag_settle_after is not None:
            try:
                self._root.after_cancel(self._drag_settle_after)
            except tk.TclError:
                pass
        self._drag_settle_after = self._root.after(150, self._on_drag_settled)

        # Also maintain the legacy root_configure_after (shorter window used by
        # callers that want an early settle signal)
        if self._root_configure_after is not None:
            try:
                self._root.after_cancel(self._root_configure_after)
            except tk.TclError:
                pass
        self._root_configure_after = self._root.after(100, self._do_root_configure)

    def _do_root_configure(self) -> None:
        """Deferred root-configure settle -- runs once per 100 ms idle window."""
        self._root_configure_after = None
        # No-op for now; the method exists so future global resize logic can be
        # added here without introducing a new un-debounced Configure binding.

    def _on_drag_settled(self) -> None:
        """Fires 150 ms after the last root Configure event.

        Clears _drag_active and fires any pending canvas-configure callbacks
        that were skipped during the drag.  This ensures the layout is correct
        after the user releases the window edge, without having done unnecessary
        work on every intermediate pixel.
        """
        self._drag_settle_after = None
        self._drag_active = False

        # Fire all pending canvas-configure callbacks accumulated during drag
        pending = self._pending_canvas_configures[:]
        self._pending_canvas_configures.clear()
        for cb in pending:
            try:
                cb()
            except Exception:  # noqa: BLE001
                pass

    # -----------------------------------------------------------------------
    # Rail labels (public, for testing)
    # -----------------------------------------------------------------------

    @property
    def rail_item_ids(self) -> list[str]:
        """Return the tool IDs present in the rail (for smoke tests)."""
        return list(self._rail_items.keys())

    @property
    def active_tool_id(self) -> str:
        return self._active_id

    # -----------------------------------------------------------------------
    # Font helpers
    # -----------------------------------------------------------------------

    def _small_font(self) -> tkfont.Font:
        return tkfont.Font(family=self._fonts.sans_family, size=tokens.FS_12)

    def _rail_font(self) -> tkfont.Font:
        return tkfont.Font(family=self._fonts.sans_family, size=tokens.FS_13)

    def _group_header_font(self) -> tkfont.Font:
        return tkfont.Font(family=self._fonts.sans_family, size=tokens.FS_12, weight="bold")
