"""TkShell — the top-level window chrome, rail, status bar, and tool runner.

Responsibilities
----------------
* Win11-style title bar (title text + SF monogram chip)
* Left rail (220 px) — groups from BaseTool.group, sorted (group, order, label)
  plus static Instructions / About / User rows below a divider.
* Status bar (22 px) — live status left, version + email right.
* Content area — auto-generates each tool's frame from tool.inputs dispatched
  to the right primitive, plus output FileRow when tool.output is set.
* Primary button — disables inputs, spawns worker via ThreadPoolExecutor,
  marshals progress/completion to Tk via root.after(0, ...).
* Secondary buttons from tool.secondary_actions().
* Tool switching preserves per-tool input values in memory.
* Global exception handler → danger banner + log path.
"""

from __future__ import annotations

import logging
import tkinter as tk
import tkinter.font as tkfont
import tkinter.messagebox as messagebox
import tkinter.ttk as ttk
import traceback
from concurrent.futures import Future, ThreadPoolExecutor
from pathlib import Path
from typing import Any

from app_metadata import APP_TITLE, APP_VERSION, SUPPORT_EMAIL
from toolkit import tokens
from toolkit.base_tool import (
    BaseTool,
    CurrencyInput,
    DateInput,
    FileInput,
    InputSpec,
    NumberInput,
    OutputSpec,
    SecretInput,
    TextInput,
    ToolResult,
)
from toolkit.fonts import FontMap
from toolkit.primitives import (
    Banner,
    CurrencyField,
    DateField,
    FileRow,
    LogView,
    Metric,
    NumberField,
    ProgressBar,
    SecretField,
    SectionHeader,
    Table,
    TextField,
)
from toolkit.user_frame import UserFrame

logger = logging.getLogger(__name__)

# Type alias for the value-bearing widget dict kept per tool.
_WidgetMap = dict[str, Any]


_CASES21_PO_HELP_TEXT = """How to save a CASES21 Purchase Order as a PDF

Purchase Orders uploaded to School Tool are validated by the system. Anything \
generated directly by CASES21 or Compass is recognised automatically and \
unlocks your paid tools within seconds. To upload a CASES21 PO, you first \
need to save it out of CASES21 as a PDF. Here's how.


BEFORE YOU START

  \u2022 Make sure you are signed in to CASES21 with your usual credentials.
  \u2022 Know the PO number (or supplier / date) of the Purchase Order you \
want to save. If you've just generated the invoice through School Tool, \
look for the matching PO your school finance office raised against it.


STEP-BY-STEP

  1. In CASES21, open the Finance module.

  2. Navigate to Accounts Payable \u2192 Purchase Orders.

  3. Use the search filters (PO number, supplier name, or date range) to \
find the PO you want. Highlight the PO row in the list.

  4. Click Print (or press Ctrl+P). The Windows Print dialog opens.

  5. Under Printer, choose Microsoft Print to PDF.
     If you don't see that option, pick any PDF printer that's installed, \
or install one (Foxit Reader and PDFCreator are both free).

  6. Click Print.

  7. In the Save Print Output As window:
       \u2022 Pick a folder you'll remember (e.g. Documents \\ School Tool).
       \u2022 Name the file clearly \u2014 for example PO_P024900.pdf.
       \u2022 Click Save.

  8. In School Tool, go to User \u2192 Service \u2192 Upload signed PO and \
pick the PDF you just saved.


WHAT HAPPENS NEXT

  \u2022 If the PO was generated by CASES21 (or Compass), School Tool \
validates it instantly. You'll see the licence status flip to Active and \
your paid tools unlock right away.

  \u2022 If the PO is scanned or non-standard, it enters a manual review \
queue. We usually respond within one business day.


TROUBLESHOOTING

  \u2022 "Microsoft Print to PDF" missing \u2014 open Windows Settings \
\u2192 Apps \u2192 Optional features, search for "Microsoft Print to PDF", \
and install it. Restart the Print dialog afterwards.

  \u2022 PDF opens blank \u2014 you may have printed the list view rather \
than the PO itself. Open the PO first (double-click it), then print.

  \u2022 Upload fails in School Tool \u2014 check the file is under 10 MB \
and is actually a .pdf (not .docx or a photo). Retry from User \u2192 \
Service.


SUPPORT

  School Tool feedback \u2014 Vurctne@gmail.com
  DoE schools finance help \u2014 schools.finance.support@education.vic.gov.au
"""


class TkShell(ttk.Frame):
    """Top-level shell frame — pack into the root Tk window with fill=both, expand=True."""

    def __init__(
        self,
        root: tk.Tk,
        fonts: FontMap,
        tools: list[type[BaseTool]],
        log_path: Path | None = None,
        **kwargs: Any,
    ) -> None:
        super().__init__(root, **kwargs)

        self._root = root
        self._fonts = fonts
        self._log_path = log_path

        # Instantiate each tool class → instance
        # tools is a list[type[BaseTool]] from registry.all_tools()
        self._tools: list[BaseTool] = [cls() for cls in tools]
        self._tool_map: dict[str, BaseTool] = {t.id: t for t in self._tools}

        # Per-tool cached input values (preserved across tab switches)
        self._input_cache: dict[str, dict[str, Any]] = {t.id: {} for t in self._tools}

        # Active tool
        self._active_id: str = self._tools[0].id if self._tools else ""

        # User tab (built lazily on first activation)
        self._user_frame: UserFrame | None = None

        # Unlock CTA frame (built lazily on first gated activation)
        self._unlock_frame: tk.Frame | None = None
        self._unlock_title_var: tk.StringVar | None = None

        # Per-tool executor (one per tool instance so runs don't queue globally)
        self._executors: dict[str, ThreadPoolExecutor] = {
            t.id: ThreadPoolExecutor(max_workers=1) for t in self._tools
        }

        # Install global exception handler
        self._root.report_callback_exception = self._handle_tk_exception

        # Build layout
        self._build_layout()

        # Activate first tool
        if self._active_id:
            self._activate_tool(self._active_id)

    # -----------------------------------------------------------------------
    # Layout construction
    # -----------------------------------------------------------------------

    def _build_layout(self) -> None:
        """Construct the shell: app header | (rail | content) | status bar."""
        self.configure(style="TFrame")

        # App header row (32 px) — SF chip + active-tool title
        self._app_header = self._build_app_header()
        self._app_header.pack(side="top", fill="x")

        # Outer vertical split: body + status bar
        self._body_frame = ttk.Frame(self)
        self._body_frame.pack(side="top", fill="both", expand=True)

        self._status_bar = self._build_status_bar()
        self._status_bar.pack(side="bottom", fill="x")

        # Horizontal split inside body: rail | content
        self._rail_frame = self._build_rail()
        self._rail_frame.pack(side="left", fill="y")

        self._content_outer = tk.Frame(self._body_frame, bg=tokens.BG_MUTED)
        self._content_outer.pack(side="left", fill="both", expand=True)

        # Tool content frames (one per tool, stacked — only one visible at once)
        self._tool_frames: dict[str, tk.Frame] = {}
        self._tool_widgets: dict[str, _WidgetMap] = {}
        self._tool_banners: dict[str, Banner | None] = {}
        self._tool_progress: dict[str, ProgressBar | None] = {}
        self._tool_logviews: dict[str, LogView | None] = {}
        self._tool_tables: dict[str, Table | None] = {}
        self._tool_metric_frames: dict[str, tk.Frame | None] = {}
        self._tool_primary_btns: dict[str, ttk.Button | None] = {}
        self._tool_output_rows: dict[str, FileRow | None] = {}

        for tool in self._tools:
            frame, wmap = self._build_tool_frame(tool)
            frame.place(in_=self._content_outer, x=0, y=0, relwidth=1.0, relheight=1.0)
            frame.lower()  # hide all initially
            self._tool_frames[tool.id] = frame
            self._tool_widgets[tool.id] = wmap

    def _build_app_header(self) -> tk.Frame:
        """32 px app-level header — navy SF chip with active tool's short mark + title text.

        Sits above the body; OS chrome sits above this. Matches the design handoff's
        ``desktop_multitool/tk-shell.jsx`` artboard (chip + title, no custom min/max/close).
        """
        header = tk.Frame(self, bg=tokens.BG_MUTED, height=32)
        header.pack_propagate(False)

        inner = tk.Frame(header, bg=tokens.BG_MUTED)
        inner.pack(fill="both", expand=True, padx=tokens.SP_3)

        # SF monogram chip: 16x16 navy square with the active tool's short mark.
        # Height is clamped via a frame wrapper so the label renders at exactly 16 px.
        chip_wrap = tk.Frame(inner, bg=tokens.BG_MUTED, width=16, height=16)
        chip_wrap.pack_propagate(False)
        chip_wrap.pack(side="left", pady=(tokens.SP_2, tokens.SP_2))

        self._header_chip = tk.Label(
            chip_wrap,
            text="",
            bg=tokens.BRAND_NAVY,
            fg=tokens.FG_INVERSE,
            font=tkfont.Font(family=self._fonts.sans_family, size=8, weight="bold"),
            anchor="center",
        )
        self._header_chip.pack(fill="both", expand=True)

        # Title text — updated on tool activation.
        self._header_title_var = tk.StringVar(value=APP_TITLE)
        tk.Label(
            inner,
            textvariable=self._header_title_var,
            bg=tokens.BG_MUTED,
            fg=tokens.FG_1,
            font=tkfont.Font(family=self._fonts.sans_family, size=tokens.FS_12),
            anchor="w",
        ).pack(side="left", padx=(tokens.SP_3, 0))

        # 1 px bottom border
        tk.Frame(header, bg=tokens.BORDER_SUBTLE, height=1).pack(side="bottom", fill="x")

        return header

    def _build_status_bar(self) -> tk.Frame:
        bar = tk.Frame(
            self._body_frame,
            bg=tokens.BG_MUTED,
            height=22,
        )
        bar.pack_propagate(False)

        # 1 px top border
        sep = tk.Frame(bar, bg=tokens.BORDER_SUBTLE, height=1)
        sep.pack(side="top", fill="x")

        inner = tk.Frame(bar, bg=tokens.BG_MUTED)
        inner.pack(fill="both", expand=True, padx=tokens.SP_3)

        self._status_left_var = tk.StringVar(value="Ready")
        left = tk.Label(
            inner,
            textvariable=self._status_left_var,
            fg=tokens.FG_MUTED,
            bg=tokens.BG_MUTED,
            font=self._small_font(),
            anchor="w",
        )
        left.pack(side="left", fill="x", expand=True)

        right_text = f"v{APP_VERSION} \u00b7 {SUPPORT_EMAIL}"
        right = tk.Label(
            inner,
            text=right_text,
            fg=tokens.FG_MUTED,
            bg=tokens.BG_MUTED,
            font=self._small_font(),
            anchor="e",
        )
        right.pack(side="right")

        return bar

    def _build_rail(self) -> tk.Frame:
        """Build the 220 px left rail with grouped tool entries."""
        rail = tk.Frame(
            self._body_frame,
            bg=tokens.BG_PANEL,
            width=220,
        )
        rail.pack_propagate(False)

        # 1 px right border
        border = tk.Frame(rail, bg=tokens.BORDER_SUBTLE, width=1)
        border.pack(side="right", fill="y")

        scroll_container = tk.Frame(rail, bg=tokens.BG_PANEL)
        scroll_container.pack(side="left", fill="both", expand=True, pady=tokens.SP_1)

        # Group tools
        groups: dict[str, list[BaseTool]] = {}
        for tool in sorted(self._tools, key=lambda t: (t.group, t.order, t.label)):
            groups.setdefault(tool.group, []).append(tool)

        self._rail_items: dict[str, tk.Label] = {}

        for group_name, group_tools in groups.items():
            # Group header
            grp_lbl = tk.Label(
                scroll_container,
                text=f"\u25be {group_name}",
                bg=tokens.BG_PANEL,
                fg=tokens.FG_1,
                font=self._group_header_font(),
                anchor="w",
                padx=tokens.SP_2,
                pady=tokens.SP_1,
            )
            grp_lbl.pack(fill="x")

            for tool in group_tools:
                item = tk.Label(
                    scroll_container,
                    text=tool.label,
                    bg=tokens.BG_PANEL,
                    fg=tokens.FG_1,
                    font=self._rail_font(),
                    anchor="w",
                    padx=30,
                    pady=tokens.SP_1,
                    cursor="hand2",
                )
                item.pack(fill="x")
                tid = tool.id
                item.bind("<Button-1>", lambda _e, t=tid: self._activate_tool(t))  # type: ignore[misc]
                item.bind("<Enter>", lambda _e, w=item, t=tid: self._rail_hover(w, t))  # type: ignore[misc]
                item.bind("<Leave>", lambda _e, w=item, t=tid: self._rail_unhover(w, t))  # type: ignore[misc]
                self._rail_items[tool.id] = item

        # Divider
        div = tk.Frame(scroll_container, bg=tokens.BORDER_SUBTLE, height=1)
        div.pack(fill="x", padx=tokens.SP_3, pady=(tokens.SP_2, tokens.SP_1))

        # Static entries: Instructions, About, User
        for entry_label, callback in [
            ("Instructions", self._show_instructions),
            ("About", self._show_about),
            ("User", self._show_user),
        ]:
            lbl = tk.Label(
                scroll_container,
                text=entry_label,
                bg=tokens.BG_PANEL,
                fg=tokens.FG_1,
                font=self._rail_font(),
                anchor="w",
                padx=tokens.SP_3,
                pady=3,
                cursor="hand2",
            )
            lbl.pack(fill="x")
            lbl.bind("<Button-1>", lambda _e, cb=callback: cb())  # type: ignore[misc]

        return rail

    def _build_tool_frame(self, tool: BaseTool) -> tuple[tk.Frame, _WidgetMap]:
        """Build the full content frame for a single tool. Returns (frame, widget_map)."""
        frame = tk.Frame(self._content_outer, bg=tokens.BG_MUTED)
        widget_map: _WidgetMap = {}

        # Scrollable canvas for the content
        canvas = tk.Canvas(frame, bg=tokens.BG_MUTED, highlightthickness=0)
        vsb = ttk.Scrollbar(frame, orient="vertical", command=canvas.yview)
        canvas.configure(yscrollcommand=vsb.set)

        vsb.pack(side="right", fill="y")
        canvas.pack(side="left", fill="both", expand=True)

        inner = tk.Frame(canvas, bg=tokens.BG_MUTED)
        canvas_window = canvas.create_window((0, 0), window=inner, anchor="nw")

        def _on_inner_configure(_e: Any) -> None:
            canvas.configure(scrollregion=canvas.bbox("all"))

        def _on_canvas_configure(e: Any) -> None:
            canvas.itemconfigure(canvas_window, width=e.width)

        inner.bind("<Configure>", _on_inner_configure)
        canvas.bind("<Configure>", _on_canvas_configure)

        pad = tokens.SP_4  # 16 px
        gap = tokens.SP_GAP_SECTION  # 10 px per design spec

        def section(pady_top: int = 0) -> tk.Frame:
            f = tk.Frame(inner, bg=tokens.BG_MUTED)
            f.pack(fill="x", padx=pad, pady=(pady_top, 0))
            return f

        # Section header
        hdr_frame = section(pad)
        sh = SectionHeader(hdr_frame, title=tool.label)
        sh.pack(fill="x")

        has_output = tool.output is not None

        # Input fields
        for inp in tool.inputs:
            inp_frame = section(gap)
            w = self._build_input_widget(inp_frame, inp, tool)
            w.pack(fill="x")
            widget_map[inp.key] = w

        # Output file row (only when tool.output is set)
        output_row: FileRow | None = None
        if has_output and tool.output is not None:
            out_spec: OutputSpec = tool.output
            out_frame = section(gap)
            out_row_label = out_spec.label or "Output file"

            def _on_output_pick(p: Path, key: str = out_spec.key) -> None:
                self._input_cache[tool.id][key] = p

            output_row = FileRow(
                out_frame,
                label=out_row_label,
                on_pick=_on_output_pick,
                filetypes=[
                    (f"{out_spec.suffix.lstrip('.')} files", f"*{out_spec.suffix}"),
                    ("All files", "*.*"),
                ],
                optional=False,
            )
            output_row.pack(fill="x")

        self._tool_output_rows[tool.id] = output_row

        # --- Action button row ---
        btn_frame = section(gap + tokens.SP_1)
        btn_inner = tk.Frame(btn_frame, bg=tokens.BG_MUTED)
        btn_inner.pack(anchor="w")

        primary_btn: ttk.Button = ttk.Button(
            btn_inner,
            text=tool.primary_button,
            command=lambda t=tool: self._run_tool(t),  # type: ignore[misc]
            style="Accent.TButton",
        )
        primary_btn.pack(side="left", padx=(0, tokens.SP_2))
        self._tool_primary_btns[tool.id] = primary_btn

        # Secondary actions
        for sec_label, sec_cmd in tool.secondary_actions():
            sec_btn = ttk.Button(btn_inner, text=sec_label, command=sec_cmd)
            sec_btn.pack(side="left", padx=(0, tokens.SP_1))

        # --- Banner (hidden until result) ---
        banner_frame = section(gap)
        banner: Banner | None = None
        self._tool_banners[tool.id] = banner
        widget_map["__banner_frame__"] = banner_frame

        # --- Progress bar (hidden until running) ---
        pb_frame = section(gap)
        pb = ProgressBar(pb_frame)
        pb.pack(fill="x")
        pb_frame.pack_forget()  # hidden initially
        self._tool_progress[tool.id] = pb
        widget_map["__pb_frame__"] = pb_frame

        # --- Metric area (populated after run) ---
        metric_frame = section(gap)
        metric_frame.pack_forget()
        self._tool_metric_frames[tool.id] = metric_frame

        # --- Log view ---
        log_frame = section(gap)
        lv = LogView(log_frame)
        lv.pack(fill="both", expand=True)
        log_frame.pack_forget()
        self._tool_logviews[tool.id] = lv
        widget_map["__log_frame__"] = log_frame

        # --- Table ---
        table_frame = section(gap)
        self._tool_tables[tool.id] = None  # created lazily on result
        widget_map["__table_frame__"] = table_frame
        table_frame.pack_forget()

        # --- Muted footer ---
        footer_frame = section(gap)
        footer = tk.Label(
            footer_frame,
            text=f"Please send feedback to {SUPPORT_EMAIL}",
            fg=tokens.FG_3,
            bg=tokens.BG_MUTED,
            font=self._small_font(),
            anchor="w",
        )
        footer.pack(fill="x", pady=(0, pad))

        return frame, widget_map

    def _build_input_widget(self, parent: tk.Widget, inp: InputSpec, tool: BaseTool) -> tk.Widget:
        """Dispatch an InputSpec → the matching primitive widget."""
        if isinstance(inp, FileInput):
            cached = self._input_cache[tool.id].get(inp.key)

            def _on_pick(p: Path, key: str = inp.key, tid: str = tool.id) -> None:
                self._input_cache[tid][key] = p

            return FileRow(
                parent,
                label=inp.label,
                on_pick=_on_pick,
                filetypes=inp.filetypes if inp.filetypes else [("All files", "*.*")],
                initial_path=cached if isinstance(cached, Path) else None,
            )

        if isinstance(inp, TextInput):
            cached = str(self._input_cache[tool.id].get(inp.key, ""))
            return TextField(
                parent,
                label=inp.label,
                value=cached,
                placeholder=inp.placeholder,
                max_length=inp.max_length,
            )

        if isinstance(inp, NumberInput):
            cached = str(self._input_cache[tool.id].get(inp.key, ""))
            return NumberField(
                parent,
                label=inp.label,
                value=cached,
                min_value=inp.min_value,
                max_value=inp.max_value,
                decimals=inp.decimals,
            )

        if isinstance(inp, CurrencyInput):
            cached = str(self._input_cache[tool.id].get(inp.key, ""))
            return CurrencyField(parent, label=inp.label, value=cached)

        if isinstance(inp, DateInput):
            return DateField(parent, label=inp.label, default=inp.default)

        if isinstance(inp, SecretInput):
            return SecretField(
                parent,
                label=inp.label,
                pattern=inp.pattern,
                remember_key=inp.remember_key,
            )

        # Fallback (should never happen with a well-typed InputSpec)
        return TextField(parent, label=getattr(inp, "label", str(inp)))

    # -----------------------------------------------------------------------
    # Tool activation
    # -----------------------------------------------------------------------

    def _activate_tool(self, tool_id: str) -> None:
        if tool_id not in self._tool_frames:
            return

        self._active_id = tool_id
        tool = self._tool_map[tool_id]

        # Update rail selection styling
        for tid, lbl in self._rail_items.items():
            if tid == tool_id:
                lbl.configure(bg=tokens.RAIL_SELECTED, fg=tokens.FG_INVERSE)
            else:
                lbl.configure(bg=tokens.BG_PANEL, fg=tokens.FG_1)

        # Update root window title
        self._root.title(f"{APP_TITLE} \u2014 {tool.label}")

        # Update in-app header: chip reflects active tool's short mark + title text
        self._header_chip.configure(text=tool.short)
        self._header_title_var.set(f"{APP_TITLE} \u2014 {tool.label}")

        # Licence gate — check before lifting the tool frame
        feature = getattr(tool, "requires_feature", None)
        if feature is not None:
            import toolkit.licence as _licence  # noqa: PLC0415  (lazy import)

            status = _licence.read_status()
            if status.state not in {"active", "grace"}:
                self._show_unlock_cta(tool)
                self._set_status("Ready")
                logger.info("Licence gate blocked tool: %s (%s)", tool.label, tool_id)
                return
            if status.state == "grace":
                logger.warning(
                    "Licence in grace period — allowing tool: %s (%s)",
                    tool.label,
                    tool_id,
                )

        # Show/hide content frames
        for frame in self._tool_frames.values():
            frame.lower()
        if self._unlock_frame is not None:
            self._unlock_frame.lower()
        self._tool_frames[tool_id].lift()

        self._set_status("Ready")
        logger.info("Activated tool: %s (%s)", tool.label, tool_id)

    def _show_unlock_cta(self, tool: BaseTool) -> None:
        """Render the unlock CTA frame in place of the tool's content frame."""
        # Hide all tool content frames
        for frame in self._tool_frames.values():
            frame.lower()

        # Build the unlock frame lazily
        if self._unlock_frame is None:
            self._unlock_frame = tk.Frame(self._content_outer, bg=tokens.BG_MUTED)
            self._unlock_frame.place(
                in_=self._content_outer, x=0, y=0, relwidth=1.0, relheight=1.0
            )

            pad = tokens.SP_4

            self._unlock_title_var = tk.StringVar(value=tool.label)

            hdr_frame = tk.Frame(self._unlock_frame, bg=tokens.BG_MUTED)
            hdr_frame.pack(fill="x", padx=pad, pady=(pad, 0))

            import tkinter.font as _tkfont  # noqa: PLC0415

            tk.Label(
                hdr_frame,
                textvariable=self._unlock_title_var,
                font=_tkfont.Font(
                    family=self._fonts.sans_family, size=tokens.FS_16, weight="bold"
                ),
                fg=tokens.FG_1,
                bg=tokens.BG_MUTED,
                anchor="w",
            ).pack(fill="x")
            tk.Label(
                hdr_frame,
                text="This tool requires an active licence.",
                font=_tkfont.Font(family=self._fonts.sans_family, size=tokens.FS_13),
                fg=tokens.FG_MUTED,
                bg=tokens.BG_MUTED,
                anchor="w",
                wraplength=820,
                justify="left",
            ).pack(fill="x", pady=(tokens.SP_1, 0))

            banner_frame = tk.Frame(self._unlock_frame, bg=tokens.BG_MUTED)
            banner_frame.pack(fill="x", padx=pad, pady=(tokens.SP_GAP_SECTION, 0))
            Banner(
                banner_frame,
                level="info",
                text=(
                    "Get started with School Tool Pro in three steps: "
                    "1. Sign in  \u00b7  2. Generate an annual invoice  \u00b7  "
                    "3. Upload your Purchase Order. "
                    "Your tool unlocks as soon as your PO is validated."
                ),
            ).pack(fill="x")

            # Instant-validation note for Compass / CASES21 POs.
            note_frame = tk.Frame(self._unlock_frame, bg=tokens.BG_MUTED)
            note_frame.pack(fill="x", padx=pad, pady=(tokens.SP_GAP_SECTION, 0))
            Banner(
                note_frame,
                level="ok",
                text=(
                    "Purchase Orders exported directly from Compass or CASES21 "
                    "are validated instantly by the system \u2014 no waiting for "
                    "manual review. Scanned or non-standard POs are reviewed "
                    "within one business day."
                ),
            ).pack(fill="x")

            btn_frame = tk.Frame(self._unlock_frame, bg=tokens.BG_MUTED)
            btn_frame.pack(fill="x", padx=pad, pady=(tokens.SP_GAP_SECTION, 0))

            ttk.Button(
                btn_frame,
                text="Go to User tab",
                style="Accent.TButton",
                command=self._activate_user_tab,
            ).pack(side="left", padx=(0, tokens.SP_2))

            ttk.Button(
                btn_frame,
                text="How to save a CASES21 PO",
                command=self._show_cases21_po_help,
            ).pack(side="left", padx=(0, tokens.SP_2))

            tk.Label(
                btn_frame,
                text="Already paid? Try \u201cRefresh licence\u201d in User \u2192 Service.",
                fg=tokens.FG_MUTED,
                bg=tokens.BG_MUTED,
                font=self._small_font(),
                anchor="w",
            ).pack(side="left")
        else:
            # Update the title for whichever paid tool was clicked
            if self._unlock_title_var is not None:
                self._unlock_title_var.set(tool.label)

        # Bring the unlock frame to the top
        self._unlock_frame.lift()

    def _show_cases21_po_help(self) -> None:
        """Open a scrollable dialog with step-by-step instructions for saving
        a Purchase Order out of CASES21 as a PDF ready to upload."""
        title = "How to save a CASES21 Purchase Order"
        body = _CASES21_PO_HELP_TEXT
        self._show_help_window(title, body)

    # -----------------------------------------------------------------------
    # Rail hover effects
    # -----------------------------------------------------------------------

    def _rail_hover(self, widget: tk.Label, tool_id: str) -> None:
        if tool_id != self._active_id:
            widget.configure(bg=tokens.BG_RAIL_HOVER)

    def _rail_unhover(self, widget: tk.Label, tool_id: str) -> None:
        if tool_id == self._active_id:
            widget.configure(bg=tokens.RAIL_SELECTED, fg=tokens.FG_INVERSE)
        else:
            widget.configure(bg=tokens.BG_PANEL, fg=tokens.FG_1)

    # -----------------------------------------------------------------------
    # Static rail entries
    # -----------------------------------------------------------------------

    def _show_instructions(self) -> None:
        """Open a scrollable window showing the active tool's built-in help text.

        Tools expose their help via a ``help_text`` class attribute. If the
        active tool doesn't define one, a friendly fallback is shown.
        """
        tool = self._tool_map.get(self._active_id)
        help_text: str | None = getattr(tool, "help_text", None) if tool else None
        title = f"{tool.label} \u2014 Instructions" if tool else "Instructions"

        if not help_text:
            messagebox.showinfo(
                "Instructions",
                "No instructions have been written for this tool yet.\n\n"
                f"If you'd like documentation here, email {SUPPORT_EMAIL}.",
            )
            return

        self._show_help_window(title, help_text)

    def _show_help_window(self, title: str, help_text: str) -> None:
        """Render ``help_text`` in a dedicated scrollable modal window with a
        navy header strip, heading/mono tagging, and live colour swatches for
        any ``#RRGGBB`` hex codes in the body.
        """
        # Build a dedicated modal window with a scrollable read-only Text widget.
        win = tk.Toplevel(self._root)
        win.title(title)
        win.geometry("720x640")
        win.minsize(560, 400)
        win.transient(self._root)
        win.configure(bg=tokens.BG_PANEL)

        # Header strip (navy band with the tool label)
        header = tk.Frame(win, bg=tokens.BRAND_NAVY, height=48)
        header.pack(side="top", fill="x")
        header.pack_propagate(False)
        tk.Label(
            header,
            text=title,
            bg=tokens.BRAND_NAVY,
            fg=tokens.FG_INVERSE,
            font=tkfont.Font(family=self._fonts.sans_family, size=tokens.FS_14, weight="bold"),
            anchor="w",
            padx=tokens.SP_4,
        ).pack(fill="both", expand=True)

        # Body: scrollable Text
        body = tk.Frame(win, bg=tokens.BG_PANEL)
        body.pack(side="top", fill="both", expand=True, padx=tokens.SP_4, pady=tokens.SP_3)

        yscroll = ttk.Scrollbar(body, orient="vertical")
        yscroll.pack(side="right", fill="y")

        text = tk.Text(
            body,
            wrap="word",
            bg=tokens.BG_PANEL,
            fg=tokens.FG_1,
            relief="flat",
            borderwidth=0,
            padx=tokens.SP_3,
            pady=tokens.SP_3,
            font=tkfont.Font(family=self._fonts.sans_family, size=tokens.FS_13),
            yscrollcommand=yscroll.set,
        )
        yscroll.configure(command=text.yview)
        text.pack(side="left", fill="both", expand=True)

        # Tag configuration for emphasis
        text.tag_configure(
            "heading",
            font=tkfont.Font(family=self._fonts.sans_family, size=tokens.FS_14, weight="bold"),
            foreground=tokens.BRAND_NAVY,
            spacing1=12,
            spacing3=4,
        )
        text.tag_configure(
            "mono",
            font=tkfont.Font(family=self._fonts.mono_family, size=tokens.FS_13),
        )

        # Any "#RRGGBB" hex code in the body gets a live colour swatch
        # embedded inline (so the reader sees the actual colour, not just
        # the code).
        import re as _re

        hex_re = _re.compile(r"#[0-9A-Fa-f]{6}\b")

        def _insert_line_with_swatches(raw_line: str, tag: str | None) -> None:
            """Insert ``raw_line`` into the Text widget. Every ``#RRGGBB`` hex
            code is **replaced** by a small colour rectangle (the user sees the
            actual colour, not the code)."""
            pos = 0
            for match in hex_re.finditer(raw_line):
                start, end = match.span()
                if start > pos:
                    segment = raw_line[pos:start]
                    if tag:
                        text.insert("end", segment, tag)
                    else:
                        text.insert("end", segment)
                hex_code = match.group(0).upper()
                # Small 14x12 swatch with a subtle 1 px border.
                swatch = tk.Frame(
                    text,
                    bg=hex_code,
                    width=14,
                    height=12,
                    highlightthickness=1,
                    highlightbackground=tokens.BORDER_SUBTLE,
                )
                swatch.pack_propagate(False)
                text.window_create("end", window=swatch, padx=0, pady=0)
                # Hex code itself is intentionally NOT inserted — the swatch
                # alone communicates the colour; showing raw codes clutters
                # the prose.
                pos = end
            tail = raw_line[pos:] + "\n"
            if tag:
                text.insert("end", tail, tag)
            else:
                text.insert("end", tail)

        # Lines in ALL-CAPS are treated as headings; indented lines (4 spaces)
        # are treated as monospace blocks.
        for line in help_text.splitlines():
            stripped = line.strip()
            is_heading = bool(stripped) and stripped == stripped.upper() and any(
                c.isalpha() for c in stripped
            ) and len(stripped) > 2
            is_mono = line.startswith("    ")
            if is_heading:
                _insert_line_with_swatches(line, "heading")
            elif is_mono:
                _insert_line_with_swatches(line, "mono")
            else:
                _insert_line_with_swatches(line, None)

        text.configure(state="disabled")  # read-only

        # Footer: Close button
        footer = tk.Frame(win, bg=tokens.BG_PANEL)
        footer.pack(side="bottom", fill="x", padx=tokens.SP_4, pady=tokens.SP_3)
        ttk.Button(footer, text="Close", command=win.destroy).pack(side="right")

        # Centre on the main window, modal-style focus
        win.update_idletasks()
        x = self._root.winfo_rootx() + (self._root.winfo_width() - win.winfo_width()) // 2
        y = self._root.winfo_rooty() + (self._root.winfo_height() - win.winfo_height()) // 2
        win.geometry(f"+{max(x, 0)}+{max(y, 0)}")
        win.grab_set()
        win.focus_set()

    def _show_about(self) -> None:
        messagebox.showinfo(
            "About",
            f"{APP_TITLE}\nSupport: {SUPPORT_EMAIL}",
        )

    def _show_user(self) -> None:
        self._activate_user_tab()

    def _activate_user_tab(self) -> None:
        """Lift the UserFrame into the content area, building it lazily."""
        if self._user_frame is None:
            self._user_frame = UserFrame(
                self._content_outer,
                fonts=self._fonts,
            )
            self._user_frame.place(
                in_=self._content_outer, x=0, y=0, relwidth=1.0, relheight=1.0
            )

        # Hide all tool frames AND the unlock CTA before lifting the user frame.
        for frame in self._tool_frames.values():
            frame.lower()
        if self._unlock_frame is not None:
            self._unlock_frame.lower()
        self._user_frame.lift()

        # Update title and SF chip
        self._root.title(f"{APP_TITLE} \u2014 User")
        self._header_chip.configure(text="US")
        self._header_title_var.set(f"{APP_TITLE} \u2014 User")

        # De-select any highlighted tool in the rail
        for lbl in self._rail_items.values():
            lbl.configure(bg=tokens.BG_PANEL, fg=tokens.FG_1)

        self._set_status("Ready")
        self._user_frame.refresh()
        logger.info("Activated User tab")

    # -----------------------------------------------------------------------
    # Status bar
    # -----------------------------------------------------------------------

    def _set_status(self, message: str) -> None:
        self._status_left_var.set(message)

    # -----------------------------------------------------------------------
    # Tool runner
    # -----------------------------------------------------------------------

    def _run_tool(self, tool: BaseTool) -> None:
        tid = tool.id

        # Gather input values from widgets
        wmap = self._tool_widgets[tid]
        resolved: dict[str, Any] = {}

        for inp in tool.inputs:
            w = wmap.get(inp.key)
            if w is None:
                continue
            if isinstance(inp, FileInput) and isinstance(w, FileRow):
                p = w.get_path()
                if p:
                    resolved[inp.key] = p
                    self._input_cache[tid][inp.key] = p
            elif isinstance(inp, TextInput) and isinstance(w, TextField):
                resolved[inp.key] = w.get()
                self._input_cache[tid][inp.key] = w.get()
            elif isinstance(inp, NumberInput) and isinstance(w, NumberField):
                from decimal import Decimal

                raw = w.get()
                try:
                    resolved[inp.key] = Decimal(raw) if inp.decimals else int(raw)
                except Exception:
                    resolved[inp.key] = raw
                self._input_cache[tid][inp.key] = raw
            elif isinstance(inp, CurrencyInput) and isinstance(w, CurrencyField):
                from decimal import Decimal

                raw = w.get()
                try:
                    resolved[inp.key] = Decimal(raw)
                except Exception:
                    resolved[inp.key] = Decimal("0")
                self._input_cache[tid][inp.key] = raw
            elif isinstance(inp, DateInput) and isinstance(w, DateField):
                resolved[inp.key] = w.get_date()
                self._input_cache[tid][inp.key] = w.get_date()
            elif isinstance(inp, SecretInput) and isinstance(w, SecretField):
                resolved[inp.key] = w.get()

        # Add output path if present
        out_row = self._tool_output_rows.get(tid)
        if out_row and tool.output:
            out_path = out_row.get_path()
            if out_path:
                resolved[tool.output.key] = out_path

        # Disable inputs + show progress bar
        self._set_inputs_state(tid, "disabled")
        pb_frame = wmap.get("__pb_frame__")
        if pb_frame:
            pb_frame.pack(fill="x", padx=tokens.SP_4, pady=(tokens.SP_2, 0))
        pb = self._tool_progress.get(tid)
        if pb:
            pb.set(0, "Starting…")

        # Clear previous results
        self._clear_results(tid)

        self._set_status("Running…")
        logger.info("Starting tool: %s", tool.label)

        executor = self._executors[tid]

        def _progress_worker(pct: int, msg: str) -> None:
            self._root.after(0, lambda: self._on_progress(tid, pct, msg))

        def _worker() -> ToolResult:
            return tool.run(resolved, _progress_worker)

        future: Future[ToolResult] = executor.submit(_worker)
        future.add_done_callback(
            lambda f: self._root.after(0, lambda: self._on_tool_complete(tid, f))
        )

    def _on_progress(self, tid: str, pct: int, msg: str) -> None:
        if tid != self._active_id:
            return
        pb = self._tool_progress.get(tid)
        if pb:
            pb.set(pct, msg)
        self._set_status(msg)

    def _on_tool_complete(self, tid: str, future: Future[ToolResult]) -> None:
        # Re-enable inputs
        self._set_inputs_state(tid, "normal")

        exc = future.exception()
        if exc is not None:
            logger.exception("Tool %s raised an exception", tid, exc_info=exc)
            result = ToolResult(
                status="error",
                banner_level="danger",
                banner_text=f"Error: {exc}",
            )
        else:
            result = future.result()

        self._render_result(tid, result)

        # Hide progress bar
        wmap = self._tool_widgets[tid]
        pb_frame = wmap.get("__pb_frame__")
        if pb_frame:
            pb_frame.pack_forget()
        pb = self._tool_progress.get(tid)
        if pb:
            pb.set(100, result.banner_text[:80])

        self._set_status(result.banner_text[:100])
        logger.info("Tool %s completed with status %s", tid, result.status)

    def _render_result(self, tid: str, result: ToolResult) -> None:
        wmap = self._tool_widgets[tid]
        banner_frame = wmap.get("__banner_frame__")

        # Banner
        if banner_frame:
            for child in banner_frame.winfo_children():
                child.destroy()
            banner = Banner(banner_frame, level=result.banner_level, text=result.banner_text)
            banner.pack(fill="x")
            self._tool_banners[tid] = banner

        # Metrics
        metric_frame = self._tool_metric_frames.get(tid)
        if metric_frame:
            for child in metric_frame.winfo_children():
                child.destroy()
            if result.metrics:
                large_single = len(result.metrics) == 1
                metric_frame.pack(fill="x", padx=tokens.SP_4, pady=(tokens.SP_2, 0))
                row = tk.Frame(metric_frame, bg=tokens.BG_MUTED)
                row.pack(fill="x")
                for lbl, val, tone in result.metrics:
                    m = Metric(
                        row,
                        label=lbl,
                        value=val,
                        tone=tone or "neutral",
                        large=large_single,
                    )
                    m.pack(side="left", padx=(0, tokens.SP_3), expand=True)

        # Log lines
        lv = self._tool_logviews.get(tid)
        log_frame = wmap.get("__log_frame__")
        if lv and result.log_lines:
            lv.clear()
            for line in result.log_lines:
                lv.append(line)
            if log_frame:
                log_frame.pack(fill="both", expand=True, padx=tokens.SP_4, pady=(tokens.SP_2, 0))

        # Table
        table_frame = wmap.get("__table_frame__")
        if result.table_columns and result.table_rows is not None and table_frame:
            # Destroy previous table if any
            for child in table_frame.winfo_children():
                child.destroy()
            tbl = Table(table_frame, columns=result.table_columns)
            tbl.set_rows(result.table_rows)
            tbl.pack(fill="both", expand=True)
            table_frame.pack(fill="both", expand=True, padx=tokens.SP_4, pady=(tokens.SP_2, 0))
            self._tool_tables[tid] = tbl

    def _clear_results(self, tid: str) -> None:
        wmap = self._tool_widgets[tid]

        # Clear banner
        banner_frame = wmap.get("__banner_frame__")
        if banner_frame:
            for child in banner_frame.winfo_children():
                child.destroy()
        self._tool_banners[tid] = None

        # Clear metrics
        metric_frame = self._tool_metric_frames.get(tid)
        if metric_frame:
            for child in metric_frame.winfo_children():
                child.destroy()
            metric_frame.pack_forget()

        # Clear log
        lv = self._tool_logviews.get(tid)
        if lv:
            lv.clear()
        log_frame = wmap.get("__log_frame__")
        if log_frame:
            log_frame.pack_forget()

        # Clear table
        table_frame = wmap.get("__table_frame__")
        if table_frame:
            for child in table_frame.winfo_children():
                child.destroy()
            table_frame.pack_forget()
        self._tool_tables[tid] = None

    def _set_inputs_state(self, tid: str, state: str) -> None:
        """Enable or disable all input widgets and the primary button for a tool."""
        wmap = self._tool_widgets[tid]
        tool = self._tool_map[tid]

        for inp in tool.inputs:
            w = wmap.get(inp.key)
            if w is None:
                continue
            if isinstance(w, FileRow):
                w.set_state(state)
            else:
                try:
                    w.configure(state=state)
                except tk.TclError:
                    pass

        out_row = self._tool_output_rows.get(tid)
        if out_row:
            out_row.set_state(state)

        primary = self._tool_primary_btns.get(tid)
        if primary:
            primary.configure(state=state)

    # -----------------------------------------------------------------------
    # Global exception handler
    # -----------------------------------------------------------------------

    def _handle_tk_exception(
        self,
        exc_type: type[BaseException],
        exc_value: BaseException,
        exc_tb: Any,
    ) -> None:
        tb_str = "".join(traceback.format_exception(exc_type, exc_value, exc_tb))
        logger.error("Unhandled exception in Tk callback:\n%s", tb_str)

        msg = str(exc_value)
        log_hint = f"\nSee log at: {self._log_path}" if self._log_path else ""

        # Show a danger banner in the active tool frame
        if self._active_id and self._active_id in self._tool_widgets:
            wmap = self._tool_widgets[self._active_id]
            banner_frame = wmap.get("__banner_frame__")
            if banner_frame:
                for child in banner_frame.winfo_children():
                    child.destroy()
                banner = Banner(
                    banner_frame,
                    level="danger",
                    text=f"An unexpected error occurred: {msg}{log_hint}",
                )
                banner.pack(fill="x")

    # -----------------------------------------------------------------------
    # Rail labels (public, for testing)
    # -----------------------------------------------------------------------

    @property
    def rail_item_ids(self) -> list[str]:
        """Return the tool IDs present in the rail (for smoke tests)."""
        return list(self._rail_items.keys())

    @property
    def active_tool_id(self) -> str:
        return self._active_id

    # -----------------------------------------------------------------------
    # Font helpers
    # -----------------------------------------------------------------------

    def _small_font(self) -> tkfont.Font:
        return tkfont.Font(family=self._fonts.sans_family, size=tokens.FS_12)

    def _rail_font(self) -> tkfont.Font:
        return tkfont.Font(family=self._fonts.sans_family, size=tokens.FS_13)

    def _group_header_font(self) -> tkfont.Font:
        return tkfont.Font(family=self._fonts.sans_family, size=tokens.FS_12, weight="bold")
